// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         tenantId: "tenantId"
 *     }
 */
export interface UsageTenantsRequest {
    tenantId: string;
    period?: string;
}
