// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         docId: "docId",
 *         layerName: "layerName",
 *         signingId: "signingId",
 *         cms: "cms",
 *         expectedVersion: {
 *             baseSha256: "baseSha256",
 *             editsVersion: 1
 *         }
 *     }
 */
export interface DocSignaturesCompleteRequest {
    docId: string;
    layerName: string;
    signingId: string;
    /** Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead. */
    "X-Document-Password"?: string;
    cms: string;
    expectedVersion: DocSignaturesCompleteRequest.ExpectedVersion;
}

export namespace DocSignaturesCompleteRequest {
    export interface ExpectedVersion {
        baseSha256: string;
        editsVersion: number;
    }
}
