// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as CloudPDF from "../../../../../index.js";

export declare namespace MetadataClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class MetadataClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<MetadataClient.Options>;

    constructor(options: MetadataClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {CloudPDF.doc.GetMetadataRequest} request
     * @param {MetadataClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudPDF.NotFoundError}
     * @throws {@link errors.CloudPDFError}
     * @throws {@link errors.CloudPDFTimeoutError}
     *
     * @example
     *     await client.doc.metadata.get({
     *         docId: "docId",
     *         layerName: "layerName"
     *     })
     */
    public get(
        request: CloudPDF.doc.GetMetadataRequest,
        requestOptions?: MetadataClient.RequestOptions,
    ): core.HttpResponsePromise<CloudPDF.DocMetadataGet200Response> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: CloudPDF.doc.GetMetadataRequest,
        requestOptions?: MetadataClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudPDF.DocMetadataGet200Response>> {
        const { docId, layerName, "X-Document-Password": documentPassword } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Document-Password": documentPassword }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/docs/${core.url.encodePathParam(docId)}/layers/${core.url.encodePathParam(layerName)}/metadata`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CloudPDF.DocMetadataGet200Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new CloudPDF.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudPDFError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/docs/{docId}/layers/{layerName}/metadata",
        );
    }
}
