// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         tenantId: "tenantId",
 *         jti: "jti"
 *     }
 */
export interface TokensRevokeRequest {
    tenantId: string;
    jti: string;
    reason?: string;
    expiresAtSeconds?: number;
}
