// This file was auto-generated by Fern from our API Definition.

export const ExportDataFormsRequestFormat = {
    Fdf: "fdf",
    Xfdf: "xfdf",
} as const;
export type ExportDataFormsRequestFormat =
    (typeof ExportDataFormsRequestFormat)[keyof typeof ExportDataFormsRequestFormat];
