// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../../../core/requestBody.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as CloudPDF from "../../../../../index.js";

export declare namespace RedactionsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class RedactionsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<RedactionsClient.Options>;

    constructor(options: RedactionsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {CloudPDF.doc.ApplyRedactionsRequest} request
     * @param {RedactionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudPDF.BadRequestError}
     * @throws {@link CloudPDF.NotFoundError}
     * @throws {@link errors.CloudPDFError}
     * @throws {@link errors.CloudPDFTimeoutError}
     *
     * @example
     *     await client.doc.redactions.apply({
     *         docId: "docId",
     *         layerName: "layerName",
     *         body: {
     *             "key": "value"
     *         }
     *     })
     */
    public apply(
        request: CloudPDF.doc.ApplyRedactionsRequest,
        requestOptions?: RedactionsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudPDF.DocRedactionsApply200Response> {
        return core.HttpResponsePromise.fromPromise(this.__apply(request, requestOptions));
    }

    private async __apply(
        request: CloudPDF.doc.ApplyRedactionsRequest,
        requestOptions?: RedactionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudPDF.DocRedactionsApply200Response>> {
        const { docId, layerName, "X-Document-Password": documentPassword, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Document-Password": documentPassword }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/docs/${core.url.encodePathParam(docId)}/layers/${core.url.encodePathParam(layerName)}/redactions/apply`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudPDF.DocRedactionsApply200Response,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudPDF.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new CloudPDF.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudPDFError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/docs/{docId}/layers/{layerName}/redactions/apply",
        );
    }
}
