packages:
  # include packages in subfolders (change as required)
  - 'packages/**'
  - 'examples/**'
  - 'viewers/*'
  - 'website'
    # exclude the git submodule (and everything inside it)
  - '!packages/pdfium/pdfium-src/**'
  - '!packages/pdf-runtime/runtime-src/**'