// Generated by scripts/generate-api-reference.mjs. Do not edit.
export default {
  head: 'Head',
  download: 'Download',
  manifest: 'Manifest',
  render: 'Render',
  text: 'Text',
  annotations: 'Annotations',
  forms: 'Forms',
  metadata: 'Metadata',
  pages: 'Pages',
  redactions: 'Redactions',
};
