// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../../../index.js";

/**
 * Where CloudPDF pulls the bytes from. The two shapes differ in WHO supplies the authority to read, not in which storage vendor holds the file.
 */
export type DocumentsImportFromRequestSource =
    /**
     * The caller supplies the authority: a presigned S3/GCS/Azure/R2/MinIO GET, or any HTTPS endpoint the deployment import policy allows. The URL is a capability — treat it as a secret. CloudPDF never echoes its query string back in errors, logs, or stored failure reasons. */
    | CloudPDF.DocumentsImportFromRequestSource.Url
    /**
     * The operator pre-registered the authority: the request names a connection and a key inside it. Which provider backs the connection (S3, GCS, Azure Blob, filesystem, ...) is deployment configuration, never wire surface. */
    | CloudPDF.DocumentsImportFromRequestSource.Connection;

export namespace DocumentsImportFromRequestSource {
    export interface Url {
        kind: "url";
        /** The URL to fetch. Must be allowed by the deployment import policy (scheme, network range, size) and must declare a length. */
        url: string;
    }

    export interface Connection {
        kind: "connection";
        /** The operator-registered storage connection to read from. */
        connectionId: string;
        /** The object key to read, inside the connection's configured scope. At most 1024 UTF-8 bytes. */
        key: string;
        /** Pins a specific version of the object. Provider-interpreted (S3 VersionId, GCS generation, Azure version id); providers without versioning reject it. */
        revision?: string | undefined;
    }
}
