// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../../../core/requestBody.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as CloudPDF from "../../../../../index.js";

export declare namespace PagesClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class PagesClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<PagesClient.Options>;

    constructor(options: PagesClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {CloudPDF.doc.DeletePagesRequest} request
     * @param {PagesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudPDF.BadRequestError}
     * @throws {@link CloudPDF.NotFoundError}
     * @throws {@link errors.CloudPDFError}
     * @throws {@link errors.CloudPDFTimeoutError}
     *
     * @example
     *     await client.doc.pages.delete({
     *         docId: "docId",
     *         layerName: "layerName",
     *         body: {
     *             "key": "value"
     *         }
     *     })
     */
    public delete(
        request: CloudPDF.doc.DeletePagesRequest,
        requestOptions?: PagesClient.RequestOptions,
    ): core.HttpResponsePromise<CloudPDF.DocPagesDelete200Response> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: CloudPDF.doc.DeletePagesRequest,
        requestOptions?: PagesClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudPDF.DocPagesDelete200Response>> {
        const { docId, layerName, "X-Document-Password": documentPassword, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Document-Password": documentPassword }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/docs/${core.url.encodePathParam(docId)}/layers/${core.url.encodePathParam(layerName)}/pages/delete`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CloudPDF.DocPagesDelete200Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudPDF.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new CloudPDF.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudPDFError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/docs/{docId}/layers/{layerName}/pages/delete",
        );
    }

    /**
     * @param {CloudPDF.doc.FlattenPagesRequest} request
     * @param {PagesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudPDF.BadRequestError}
     * @throws {@link CloudPDF.NotFoundError}
     * @throws {@link errors.CloudPDFError}
     * @throws {@link errors.CloudPDFTimeoutError}
     *
     * @example
     *     await client.doc.pages.flatten({
     *         docId: "docId",
     *         layerName: "layerName",
     *         body: {
     *             "key": "value"
     *         }
     *     })
     */
    public flatten(
        request: CloudPDF.doc.FlattenPagesRequest,
        requestOptions?: PagesClient.RequestOptions,
    ): core.HttpResponsePromise<CloudPDF.DocPagesFlatten200Response> {
        return core.HttpResponsePromise.fromPromise(this.__flatten(request, requestOptions));
    }

    private async __flatten(
        request: CloudPDF.doc.FlattenPagesRequest,
        requestOptions?: PagesClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudPDF.DocPagesFlatten200Response>> {
        const { docId, layerName, "X-Document-Password": documentPassword, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Document-Password": documentPassword }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/docs/${core.url.encodePathParam(docId)}/layers/${core.url.encodePathParam(layerName)}/pages/flatten`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CloudPDF.DocPagesFlatten200Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudPDF.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new CloudPDF.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudPDFError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/docs/{docId}/layers/{layerName}/pages/flatten",
        );
    }

    /**
     * @param {CloudPDF.doc.MovePagesRequest} request
     * @param {PagesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudPDF.BadRequestError}
     * @throws {@link CloudPDF.NotFoundError}
     * @throws {@link errors.CloudPDFError}
     * @throws {@link errors.CloudPDFTimeoutError}
     *
     * @example
     *     await client.doc.pages.move({
     *         docId: "docId",
     *         layerName: "layerName",
     *         body: {
     *             "key": "value"
     *         }
     *     })
     */
    public move(
        request: CloudPDF.doc.MovePagesRequest,
        requestOptions?: PagesClient.RequestOptions,
    ): core.HttpResponsePromise<CloudPDF.DocPagesMove200Response> {
        return core.HttpResponsePromise.fromPromise(this.__move(request, requestOptions));
    }

    private async __move(
        request: CloudPDF.doc.MovePagesRequest,
        requestOptions?: PagesClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudPDF.DocPagesMove200Response>> {
        const { docId, layerName, "X-Document-Password": documentPassword, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Document-Password": documentPassword }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/docs/${core.url.encodePathParam(docId)}/layers/${core.url.encodePathParam(layerName)}/pages/move`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CloudPDF.DocPagesMove200Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudPDF.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new CloudPDF.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudPDFError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/docs/{docId}/layers/{layerName}/pages/move",
        );
    }

    /**
     * @param {CloudPDF.doc.RotatePagesRequest} request
     * @param {PagesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudPDF.BadRequestError}
     * @throws {@link CloudPDF.NotFoundError}
     * @throws {@link errors.CloudPDFError}
     * @throws {@link errors.CloudPDFTimeoutError}
     *
     * @example
     *     await client.doc.pages.rotate({
     *         docId: "docId",
     *         layerName: "layerName",
     *         body: {
     *             "key": "value"
     *         }
     *     })
     */
    public rotate(
        request: CloudPDF.doc.RotatePagesRequest,
        requestOptions?: PagesClient.RequestOptions,
    ): core.HttpResponsePromise<CloudPDF.DocPagesRotate200Response> {
        return core.HttpResponsePromise.fromPromise(this.__rotate(request, requestOptions));
    }

    private async __rotate(
        request: CloudPDF.doc.RotatePagesRequest,
        requestOptions?: PagesClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudPDF.DocPagesRotate200Response>> {
        const { docId, layerName, "X-Document-Password": documentPassword, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Document-Password": documentPassword }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/docs/${core.url.encodePathParam(docId)}/layers/${core.url.encodePathParam(layerName)}/pages/rotate`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CloudPDF.DocPagesRotate200Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudPDF.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new CloudPDF.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudPDFError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/docs/{docId}/layers/{layerName}/pages/rotate",
        );
    }
}
