// This file was auto-generated by Fern from our API Definition.

export const AnalysisSignaturesRequestLevel = {
    None: "none",
    Lta: "lta",
    Fill: "fill",
    Annotate: "annotate",
} as const;
export type AnalysisSignaturesRequestLevel =
    (typeof AnalysisSignaturesRequestLevel)[keyof typeof AnalysisSignaturesRequestLevel];
