// Generated by scripts/generate-api-reference.mjs. Do not edit.
export default {
  index: 'Overview',
  authentication: 'Authentication',
  deployment: 'Deployment',
  tenants: 'Tenants',
  documents: 'Tenant documents',
  tokens: 'Tokens',
  shares: 'Shares',
  'document-operations': 'Document operations',
};
