// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../../../core/requestBody.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as CloudPDF from "../../../../../index.js";

export declare namespace FormsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class FormsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<FormsClient.Options>;

    constructor(options: FormsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {CloudPDF.doc.GetFormsRequest} request
     * @param {FormsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudPDF.NotFoundError}
     * @throws {@link errors.CloudPDFError}
     * @throws {@link errors.CloudPDFTimeoutError}
     *
     * @example
     *     await client.doc.forms.get({
     *         docId: "docId",
     *         layerName: "layerName"
     *     })
     */
    public get(
        request: CloudPDF.doc.GetFormsRequest,
        requestOptions?: FormsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudPDF.DocFormsGet200Response> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: CloudPDF.doc.GetFormsRequest,
        requestOptions?: FormsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudPDF.DocFormsGet200Response>> {
        const { docId, layerName, "X-Document-Password": documentPassword } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Document-Password": documentPassword }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/docs/${core.url.encodePathParam(docId)}/layers/${core.url.encodePathParam(layerName)}/form`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CloudPDF.DocFormsGet200Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new CloudPDF.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudPDFError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/docs/{docId}/layers/{layerName}/form",
        );
    }

    /**
     * @throws {@link CloudPDF.NotFoundError}
     * @throws {@link errors.CloudPDFError}
     * @throws {@link errors.CloudPDFTimeoutError}
     */
    public exportData(
        request: CloudPDF.doc.ExportDataFormsRequest,
        requestOptions?: FormsClient.RequestOptions,
    ): core.HttpResponsePromise<core.BinaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__exportData(request, requestOptions));
    }

    private async __exportData(
        request: CloudPDF.doc.ExportDataFormsRequest,
        requestOptions?: FormsClient.RequestOptions,
    ): Promise<core.WithRawResponse<core.BinaryResponse>> {
        const { docId, layerName, format, "X-Document-Password": documentPassword } = request;
        const _queryParams: Record<string, unknown> = {
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Document-Password": documentPassword }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher<core.BinaryResponse>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/docs/${core.url.encodePathParam(docId)}/layers/${core.url.encodePathParam(layerName)}/form/data`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            responseType: "binary-response",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new CloudPDF.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudPDFError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/docs/{docId}/layers/{layerName}/form/data",
        );
    }

    /**
     * @param {CloudPDF.doc.ImportDataFormsRequest} request
     * @param {FormsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudPDF.BadRequestError}
     * @throws {@link CloudPDF.NotFoundError}
     * @throws {@link errors.CloudPDFError}
     * @throws {@link errors.CloudPDFTimeoutError}
     *
     * @example
     *     await client.doc.forms.importData({
     *         docId: "docId",
     *         layerName: "layerName",
     *         body: {
     *             "key": "value"
     *         }
     *     })
     */
    public importData(
        request: CloudPDF.doc.ImportDataFormsRequest,
        requestOptions?: FormsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudPDF.DocFormsImportData200Response> {
        return core.HttpResponsePromise.fromPromise(this.__importData(request, requestOptions));
    }

    private async __importData(
        request: CloudPDF.doc.ImportDataFormsRequest,
        requestOptions?: FormsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudPDF.DocFormsImportData200Response>> {
        const { docId, layerName, "X-Document-Password": documentPassword, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Document-Password": documentPassword }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/docs/${core.url.encodePathParam(docId)}/layers/${core.url.encodePathParam(layerName)}/form/data`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudPDF.DocFormsImportData200Response,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudPDF.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new CloudPDF.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudPDFError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/docs/{docId}/layers/{layerName}/form/data",
        );
    }

    /**
     * @param {CloudPDF.doc.ResetFormsRequest} request
     * @param {FormsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudPDF.NotFoundError}
     * @throws {@link errors.CloudPDFError}
     * @throws {@link errors.CloudPDFTimeoutError}
     *
     * @example
     *     await client.doc.forms.reset({
     *         docId: "docId",
     *         layerName: "layerName",
     *         fieldKey: "fieldKey"
     *     })
     */
    public reset(
        request: CloudPDF.doc.ResetFormsRequest,
        requestOptions?: FormsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudPDF.DocFormsReset200Response> {
        return core.HttpResponsePromise.fromPromise(this.__reset(request, requestOptions));
    }

    private async __reset(
        request: CloudPDF.doc.ResetFormsRequest,
        requestOptions?: FormsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudPDF.DocFormsReset200Response>> {
        const { docId, layerName, fieldKey, "X-Document-Password": documentPassword } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Document-Password": documentPassword }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/docs/${core.url.encodePathParam(docId)}/layers/${core.url.encodePathParam(layerName)}/form/fields/${core.url.encodePathParam(fieldKey)}/reset`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CloudPDF.DocFormsReset200Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new CloudPDF.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudPDFError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/docs/{docId}/layers/{layerName}/form/fields/{fieldKey}/reset",
        );
    }

    /**
     * @param {CloudPDF.doc.SetValueFormsRequest} request
     * @param {FormsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudPDF.BadRequestError}
     * @throws {@link CloudPDF.NotFoundError}
     * @throws {@link errors.CloudPDFError}
     * @throws {@link errors.CloudPDFTimeoutError}
     *
     * @example
     *     await client.doc.forms.setValue({
     *         docId: "docId",
     *         layerName: "layerName",
     *         fieldKey: "fieldKey",
     *         body: {
     *             "key": "value"
     *         }
     *     })
     */
    public setValue(
        request: CloudPDF.doc.SetValueFormsRequest,
        requestOptions?: FormsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudPDF.DocFormsSetValue200Response> {
        return core.HttpResponsePromise.fromPromise(this.__setValue(request, requestOptions));
    }

    private async __setValue(
        request: CloudPDF.doc.SetValueFormsRequest,
        requestOptions?: FormsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudPDF.DocFormsSetValue200Response>> {
        const { docId, layerName, fieldKey, "X-Document-Password": documentPassword, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Document-Password": documentPassword }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/docs/${core.url.encodePathParam(docId)}/layers/${core.url.encodePathParam(layerName)}/form/fields/${core.url.encodePathParam(fieldKey)}/value`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CloudPDF.DocFormsSetValue200Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudPDF.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new CloudPDF.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudPDFError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/docs/{docId}/layers/{layerName}/form/fields/{fieldKey}/value",
        );
    }
}
