/**
 * Build the runtime worker artifacts into `workers/` (a SIBLING of dist, so
 * tsdown's dist clean never wipes them and publint sees them — this script
 * runs BEFORE epdf-build):
 *
 *   - embedpdf-worker.js         self-contained ESM worker: bootstrap +
 *                              engine-services + the Emscripten glue statically
 *                              bundled; only embedpdf.wasm stays external (the
 *                              worker init message says where it lives).
 *                              This file is ALSO what strict-CSP users copy
 *                              next to embedpdf.wasm as a same-origin worker.
 *   - embedpdf-worker.source.js  the same bundle as a string module — the
 *                              default inline delivery. localEngine() lazily
 *                              imports it (its own chunk in every bundler) and
 *                              spawns a blob worker from it.
 *   - encoder-worker.js        the image-encoder worker, emitted verbatim from
 *                              src/render/encoder-worker-source.ts so the blob
 *                              and static deliveries can never drift.
 *
 * Also regenerates src/generated/wasm32-version.ts from the installed
 * @embedpdf/engine-runtime-wasm32 — pinning the default jsDelivr wasm URL to
 * the exact binary this build bundled the glue from.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import esbuild from 'esbuild';

const packageRoot = fileURLToPath(new URL('..', import.meta.url));
const workersDir = path.join(packageRoot, 'workers');

// ── wasm32 version pin ───────────────────────────────────────────────────────
const wasmPath = fileURLToPath(import.meta.resolve('@embedpdf/engine-runtime-wasm32/embedpdf.wasm'));
const wasm32PackageJson = path.resolve(path.dirname(wasmPath), '..', 'package.json');
const wasm32Version = JSON.parse(fs.readFileSync(wasm32PackageJson, 'utf8')).version;

const versionFile = path.join(packageRoot, 'src', 'generated', 'wasm32-version.ts');
const versionSource = `/**
 * REGENERATED by scripts/build-workers.mjs from the installed
 * @embedpdf/engine-runtime-wasm32 version — do not edit by hand.
 *
 * In the workspace this stays '0.0.0'; a release build regenerates it with
 * the published version, which pins the default jsDelivr wasm URL to the
 * exact binary this package was built against.
 */
export const WASM32_VERSION = '${wasm32Version}';
`;
if (fs.readFileSync(versionFile, 'utf8') !== versionSource) {
  fs.writeFileSync(versionFile, versionSource);
}

fs.mkdirSync(workersDir, { recursive: true });

// Pre-rename outputs: `files` publishes workers/ wholesale, so a stale
// unclean checkout must never ship both worker generations.
for (const legacy of ['pdfium-worker.js', 'pdfium-worker.source.js', 'pdfium-worker.source.d.ts']) {
  fs.rmSync(path.join(workersDir, legacy), { force: true });
}

// ── engine worker: self-contained bundle + string module ────────────────────
await esbuild.build({
  entryPoints: [path.join(packageRoot, 'src', 'worker', 'worker-entry.ts')],
  outfile: path.join(workersDir, 'embedpdf-worker.js'),
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2020',
  minify: true,
  legalComments: 'none',
  // The glue's own `new URL('embedpdf.wasm', import.meta.url)` fallback stays in
  // the bundle deliberately: when this file runs as a real URL worker (static
  // copy or bundler-emitted) with no explicit wasm source configured, sibling
  // resolution is exactly right. The inline blob delivery always receives an
  // explicit wasmUrl instead (see src/wasm-source.ts).
  logOverride: { 'empty-import-meta': 'silent' },
});

const workerCode = fs.readFileSync(path.join(workersDir, 'embedpdf-worker.js'), 'utf8');
fs.writeFileSync(
  path.join(workersDir, 'embedpdf-worker.source.js'),
  `// GENERATED by scripts/build-workers.mjs — workers/embedpdf-worker.js as a string.\n` +
    `export default ${JSON.stringify(workerCode)};\n`,
);
fs.writeFileSync(
  path.join(workersDir, 'embedpdf-worker.source.d.ts'),
  `/** workers/embedpdf-worker.js as a string — the inline worker delivery. */\n` +
    `declare const source: string;\nexport default source;\n`,
);

// ── encoder worker: the shared source string, verbatim ──────────────────────
const encoderBundle = await esbuild.build({
  entryPoints: [path.join(packageRoot, 'src', 'render', 'encoder-worker-source.ts')],
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2020',
  write: false,
});
const encoderModule = await import(
  `data:text/javascript;base64,${Buffer.from(encoderBundle.outputFiles[0].text).toString('base64')}`
);
fs.writeFileSync(
  path.join(workersDir, 'encoder-worker.js'),
  `// GENERATED by scripts/build-workers.mjs from src/render/encoder-worker-source.ts.\n` +
    encoderModule.encoderWorkerSource.trimStart(),
);

const size = (file) => `${(fs.statSync(path.join(workersDir, file)).size / 1024).toFixed(0)} kB`;
console.log(
  `[build-workers] wasm32@${wasm32Version} — embedpdf-worker.js ${size('embedpdf-worker.js')}, ` +
    `embedpdf-worker.source.js ${size('embedpdf-worker.source.js')}, ` +
    `encoder-worker.js ${size('encoder-worker.js')}`,
);
