// Generated by scripts/generate-api-reference.mjs. Do not edit.
export default {
  list: 'List',
  get: 'Get',
  delete: 'Delete',
  commit: 'Commit',
  download: 'Download',
  thumbnail: 'Thumbnail',
  'upload-proxy': 'Upload Proxy',
  'import-from': 'Import From',
  init: 'Init',
};
