// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as CloudPDF from "../../../index.js";
import { AnnotationsClient } from "../resources/annotations/client/Client.js";
import { FormsClient } from "../resources/forms/client/Client.js";
import { MetadataClient } from "../resources/metadata/client/Client.js";
import { PagesClient } from "../resources/pages/client/Client.js";
import { RedactionsClient } from "../resources/redactions/client/Client.js";

export declare namespace DocClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class DocClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<DocClient.Options>;
    protected _annotations: AnnotationsClient | undefined;
    protected _forms: FormsClient | undefined;
    protected _metadata: MetadataClient | undefined;
    protected _pages: PagesClient | undefined;
    protected _redactions: RedactionsClient | undefined;

    constructor(options: DocClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get annotations(): AnnotationsClient {
        return (this._annotations ??= new AnnotationsClient(this._options));
    }

    public get forms(): FormsClient {
        return (this._forms ??= new FormsClient(this._options));
    }

    public get metadata(): MetadataClient {
        return (this._metadata ??= new MetadataClient(this._options));
    }

    public get pages(): PagesClient {
        return (this._pages ??= new PagesClient(this._options));
    }

    public get redactions(): RedactionsClient {
        return (this._redactions ??= new RedactionsClient(this._options));
    }

    /**
     * @param {CloudPDF.HeadDocRequest} request
     * @param {DocClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudPDF.NotFoundError}
     * @throws {@link errors.CloudPDFError}
     * @throws {@link errors.CloudPDFTimeoutError}
     *
     * @example
     *     await client.doc.head({
     *         docId: "docId"
     *     })
     */
    public head(
        request: CloudPDF.HeadDocRequest,
        requestOptions?: DocClient.RequestOptions,
    ): core.HttpResponsePromise<CloudPDF.DocHead200Response> {
        return core.HttpResponsePromise.fromPromise(this.__head(request, requestOptions));
    }

    private async __head(
        request: CloudPDF.HeadDocRequest,
        requestOptions?: DocClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudPDF.DocHead200Response>> {
        const { docId, "X-Document-Password": documentPassword } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Document-Password": documentPassword }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/docs/${core.url.encodePathParam(docId)}/head`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CloudPDF.DocHead200Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new CloudPDF.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudPDFError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/docs/{docId}/head");
    }

    /**
     * @throws {@link CloudPDF.NotFoundError}
     * @throws {@link errors.CloudPDFError}
     * @throws {@link errors.CloudPDFTimeoutError}
     */
    public download(
        request: CloudPDF.DownloadDocRequest,
        requestOptions?: DocClient.RequestOptions,
    ): core.HttpResponsePromise<core.BinaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__download(request, requestOptions));
    }

    private async __download(
        request: CloudPDF.DownloadDocRequest,
        requestOptions?: DocClient.RequestOptions,
    ): Promise<core.WithRawResponse<core.BinaryResponse>> {
        const { docId, layerName, "X-Document-Password": documentPassword } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Document-Password": documentPassword }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher<core.BinaryResponse>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/docs/${core.url.encodePathParam(docId)}/layers/${core.url.encodePathParam(layerName)}/download`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            responseType: "binary-response",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new CloudPDF.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudPDFError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/docs/{docId}/layers/{layerName}/download",
        );
    }

    /**
     * @param {CloudPDF.ManifestDocRequest} request
     * @param {DocClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudPDF.NotFoundError}
     * @throws {@link errors.CloudPDFError}
     * @throws {@link errors.CloudPDFTimeoutError}
     *
     * @example
     *     await client.doc.manifest({
     *         docId: "docId",
     *         layerName: "layerName"
     *     })
     */
    public manifest(
        request: CloudPDF.ManifestDocRequest,
        requestOptions?: DocClient.RequestOptions,
    ): core.HttpResponsePromise<CloudPDF.DocManifest200Response> {
        return core.HttpResponsePromise.fromPromise(this.__manifest(request, requestOptions));
    }

    private async __manifest(
        request: CloudPDF.ManifestDocRequest,
        requestOptions?: DocClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudPDF.DocManifest200Response>> {
        const { docId, layerName, "X-Document-Password": documentPassword } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Document-Password": documentPassword }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/docs/${core.url.encodePathParam(docId)}/layers/${core.url.encodePathParam(layerName)}/manifest`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CloudPDF.DocManifest200Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new CloudPDF.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudPDFError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/docs/{docId}/layers/{layerName}/manifest",
        );
    }

    /**
     * Render parameters (viewport, format) pass as flat dotted query keys, e.g. `?viewport.kind=width&viewport.width=800`; the full grammar is documented with the viewer.
     *
     * @throws {@link CloudPDF.NotFoundError}
     * @throws {@link errors.CloudPDFError}
     * @throws {@link errors.CloudPDFTimeoutError}
     */
    public render(
        request: CloudPDF.RenderDocRequest,
        requestOptions?: DocClient.RequestOptions,
    ): core.HttpResponsePromise<core.BinaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__render(request, requestOptions));
    }

    private async __render(
        request: CloudPDF.RenderDocRequest,
        requestOptions?: DocClient.RequestOptions,
    ): Promise<core.WithRawResponse<core.BinaryResponse>> {
        const { docId, layerName, pon, "X-Document-Password": documentPassword } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Document-Password": documentPassword }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher<core.BinaryResponse>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/docs/${core.url.encodePathParam(docId)}/layers/${core.url.encodePathParam(layerName)}/render/pages/${core.url.encodePathParam(pon)}/data`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            responseType: "binary-response",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new CloudPDF.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudPDFError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/docs/{docId}/layers/{layerName}/render/pages/{pon}/data",
        );
    }

    /**
     * @param {CloudPDF.TextDocRequest} request
     * @param {DocClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudPDF.NotFoundError}
     * @throws {@link errors.CloudPDFError}
     * @throws {@link errors.CloudPDFTimeoutError}
     *
     * @example
     *     await client.doc.text({
     *         docId: "docId",
     *         layerName: "layerName",
     *         pon: 1
     *     })
     */
    public text(
        request: CloudPDF.TextDocRequest,
        requestOptions?: DocClient.RequestOptions,
    ): core.HttpResponsePromise<CloudPDF.DocText200Response> {
        return core.HttpResponsePromise.fromPromise(this.__text(request, requestOptions));
    }

    private async __text(
        request: CloudPDF.TextDocRequest,
        requestOptions?: DocClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudPDF.DocText200Response>> {
        const { docId, layerName, pon, "X-Document-Password": documentPassword } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Document-Password": documentPassword }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/docs/${core.url.encodePathParam(docId)}/layers/${core.url.encodePathParam(layerName)}/text/pages/${core.url.encodePathParam(pon)}/data`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CloudPDF.DocText200Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new CloudPDF.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudPDFError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/docs/{docId}/layers/{layerName}/text/pages/{pon}/data",
        );
    }
}
