// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         tenantId: "tenantId",
 *         shareId: "shareId"
 *     }
 */
export interface GetSharesRequest {
    tenantId: string;
    shareId: string;
}
