// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         tenantId: "tenantId",
 *         shareId: "shareId"
 *     }
 */
export interface SharesUpdateRequest {
    tenantId: string;
    shareId: string;
    scope?: string[];
    origins?: string[] | null;
    password?: string | null;
    sessionTtlSeconds?: number;
    disabled?: boolean;
    expiresAt?: number | null;
}
