// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         shareToken: "shareToken"
 *     }
 */
export interface SharesExchangeRequest {
    shareToken: string;
    password?: string;
}
