/**
 * The bundler-facing wasm location contract (`@embedpdf/engine-runtime-wasm32/wasm-url`).
 *
 * Bundlers that support the static `new URL(..., import.meta.url)` asset form
 * (webpack 5 / Next, Vite build, Turbopack, Rspack, Parcel 2) resolve this at
 * BUILD time: they copy `lib/embedpdf.wasm` into the application's build output
 * and rewrite this expression to the emitted asset's URL. That is what makes
 * `localEngine()` zero-config — the wasm ships inside the consumer's build,
 * versioned in lockstep with node_modules, no CDN involved.
 *
 * Toolchains that leave the expression untouched resolve it at RUNTIME against
 * wherever this file actually lives — correct for native ESM served from real
 * files (e.g. a CDN mirroring the npm layout), wrong for flattened bundles
 * (plain esbuild), where the resulting fetch fails and the engine falls back
 * to its pinned CDN URL (see @embedpdf/engine's wasm-source.ts).
 *
 * Lives at the package root: lib/ is regenerated by build/compile.esm.sh.
 */
export default new URL('./lib/embedpdf.wasm', import.meta.url).href;
