// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../core/index.js";
import * as errors from "../../errors/index.js";
import type * as CloudPDF from "../index.js";

export class GoneError extends errors.CloudPDFError {
    public declare readonly body: CloudPDF.SharesExchange410Response;

    constructor(body: CloudPDF.SharesExchange410Response, rawResponse?: core.RawResponse) {
        super({
            message: "GoneError",
            statusCode: 410,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = "GoneError";
    }
}
