// Generated by scripts/generate-api-reference.mjs. Do not edit.
export default {
  get: 'Get',
  'export-data': 'Export Data',
  'import-data': 'Import Data',
  reset: 'Reset',
  'set-value': 'Set Value',
};
