// This file was auto-generated by Fern from our API Definition.

import { CloudPDFClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("DeploymentClient", () => {
    test("licenseStatus", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { license: { key: "value" }, reporting: { key: "value" }, usage: { key: "value" } };

        server
            .mockEndpoint()
            .get("/v1/deployment/license/status")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.deployment.licenseStatus();
        expect(response).toEqual(rawResponseBody);
    });
});
