// This file was auto-generated by Fern from our API Definition.

import * as CloudPDF from "../../src/api/index";
import { CloudPDFClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("DocClient", () => {
    test("head (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            baseSha: "baseSha",
            storageSizeBytes: 1,
            docVersion: 1,
            state: "pending",
            encryption: { state: "unknown", requiresPassword: true },
            permissions: {
                known: true,
                bits: 1,
                allAllowed: true,
                openedAs: "none",
                securityHandlerRevision: 1,
                canUpgradeToOwner: true,
            },
            access: { required: true, reasons: ["password"], endpoint: "endpoint" },
        };

        server
            .mockEndpoint()
            .get("/v1/docs/docId/head")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.doc.head({
            docId: "docId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("head (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/docs/docId/head")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.head({
                docId: "docId",
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });

    test("manifest (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            docVersion: 1,
            layoutVersion: 1,
            metadataVersion: 1,
            actionsVersion: 1,
            attachmentsVersion: 1,
            annotationsVersion: 1,
            auditHead: 1,
            baseSha: "baseSha",
            scopes: {
                content: "base",
                annotations: "base",
                layout: "base",
                attachments: "base",
                metadata: "base",
                actions: "base",
            },
            pages: [
                {
                    state: {
                        pageObjectNumber: 1,
                        revision: { docSessionId: "docSessionId", pageObjectNumber: 1, generation: 1 },
                        weakAnnotationState: { kind: "unknown" },
                    },
                    cache: { contentVersion: 1, annotationVersion: 1 },
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v1/docs/docId/layers/layerName/manifest")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.doc.manifest({
            docId: "docId",
            layerName: "layerName",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("manifest (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/docs/docId/layers/layerName/manifest")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.manifest({
                docId: "docId",
                layerName: "layerName",
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });

    test("text (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { text: "text", charCount: 1, charMap: [[{ key: "value" }]] };

        server
            .mockEndpoint()
            .get("/v1/docs/docId/layers/layerName/text/pages/1/data")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.doc.text({
            docId: "docId",
            layerName: "layerName",
            pon: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("text (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/docs/docId/layers/layerName/text/pages/1/data")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.text({
                docId: "docId",
                layerName: "layerName",
                pon: 1,
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });
});
