// This file was auto-generated by Fern from our API Definition.

import * as CloudPDF from "../../src/api/index";
import { CloudPDFClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SharesClient", () => {
    test("exchange (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { shareToken: "shareToken" };
        const rawResponseBody = { token: "token", docId: "docId", layerName: "layerName", expiresAt: 1.1 };

        server
            .mockEndpoint()
            .post("/v1/share-sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.shares.exchange({
            shareToken: "shareToken",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("exchange (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { shareToken: "shareToken" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/share-sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shares.exchange({
                shareToken: "shareToken",
            });
        }).rejects.toThrow(CloudPDF.BadRequestError);
    });

    test("exchange (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { shareToken: "shareToken" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/share-sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shares.exchange({
                shareToken: "shareToken",
            });
        }).rejects.toThrow(CloudPDF.ForbiddenError);
    });

    test("exchange (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { shareToken: "shareToken" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/share-sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shares.exchange({
                shareToken: "shareToken",
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });

    test("exchange (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { shareToken: "shareToken" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/share-sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shares.exchange({
                shareToken: "shareToken",
            });
        }).rejects.toThrow(CloudPDF.GoneError);
    });

    test("exchange (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { shareToken: "shareToken" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/share-sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shares.exchange({
                shareToken: "shareToken",
            });
        }).rejects.toThrow(CloudPDF.UnprocessableEntityError);
    });

    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            shares: [
                {
                    id: "id",
                    tenantId: "tenantId",
                    docId: "docId",
                    layerName: "layerName",
                    scope: ["scope"],
                    origins: ["origins"],
                    passwordProtected: true,
                    sessionTtlSeconds: 1.1,
                    disabled: true,
                    expiresAt: 1.1,
                    exchangeCount: 1.1,
                    lastExchangedAt: 1.1,
                    createdBy: "createdBy",
                    createdAt: 1.1,
                    updatedAt: 1.1,
                },
            ],
            nextCursor: "nextCursor",
        };

        server
            .mockEndpoint()
            .get("/v1/tenants/tenantId/shares")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.shares.list({
            tenantId: "tenantId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/tenants/tenantId/shares")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shares.list({
                tenantId: "tenantId",
            });
        }).rejects.toThrow(CloudPDF.BadRequestError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { docId: "docId", scope: ["scope"] };
        const rawResponseBody = {
            share: {
                id: "id",
                tenantId: "tenantId",
                docId: "docId",
                layerName: "layerName",
                scope: ["scope"],
                origins: ["origins"],
                passwordProtected: true,
                sessionTtlSeconds: 1.1,
                disabled: true,
                expiresAt: 1.1,
                exchangeCount: 1.1,
                lastExchangedAt: 1.1,
                createdBy: "createdBy",
                createdAt: 1.1,
                updatedAt: 1.1,
            },
        };

        server
            .mockEndpoint()
            .post("/v1/tenants/tenantId/shares")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.shares.create({
            tenantId: "tenantId",
            docId: "docId",
            scope: ["scope"],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { docId: "docId", scope: ["scope", "scope"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/tenants/tenantId/shares")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shares.create({
                tenantId: "tenantId",
                docId: "docId",
                scope: ["scope", "scope"],
            });
        }).rejects.toThrow(CloudPDF.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { docId: "docId", scope: ["scope", "scope"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/tenants/tenantId/shares")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shares.create({
                tenantId: "tenantId",
                docId: "docId",
                scope: ["scope", "scope"],
            });
        }).rejects.toThrow(CloudPDF.ForbiddenError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { docId: "docId", scope: ["scope", "scope"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/tenants/tenantId/shares")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shares.create({
                tenantId: "tenantId",
                docId: "docId",
                scope: ["scope", "scope"],
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            share: {
                id: "id",
                tenantId: "tenantId",
                docId: "docId",
                layerName: "layerName",
                scope: ["scope"],
                origins: ["origins"],
                passwordProtected: true,
                sessionTtlSeconds: 1.1,
                disabled: true,
                expiresAt: 1.1,
                exchangeCount: 1.1,
                lastExchangedAt: 1.1,
                createdBy: "createdBy",
                createdAt: 1.1,
                updatedAt: 1.1,
            },
        };

        server
            .mockEndpoint()
            .get("/v1/tenants/tenantId/shares/shareId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.shares.get({
            tenantId: "tenantId",
            shareId: "shareId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/tenants/tenantId/shares/shareId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shares.get({
                tenantId: "tenantId",
                shareId: "shareId",
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/v1/tenants/tenantId/shares/shareId").respondWith().statusCode(200).build();

        const response = await client.shares.delete({
            tenantId: "tenantId",
            shareId: "shareId",
        });
        expect(response).toEqual(undefined);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v1/tenants/tenantId/shares/shareId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shares.delete({
                tenantId: "tenantId",
                shareId: "shareId",
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            share: {
                id: "id",
                tenantId: "tenantId",
                docId: "docId",
                layerName: "layerName",
                scope: ["scope"],
                origins: ["origins"],
                passwordProtected: true,
                sessionTtlSeconds: 1.1,
                disabled: true,
                expiresAt: 1.1,
                exchangeCount: 1.1,
                lastExchangedAt: 1.1,
                createdBy: "createdBy",
                createdAt: 1.1,
                updatedAt: 1.1,
            },
        };

        server
            .mockEndpoint()
            .patch("/v1/tenants/tenantId/shares/shareId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.shares.update({
            tenantId: "tenantId",
            shareId: "shareId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/tenants/tenantId/shares/shareId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shares.update({
                tenantId: "tenantId",
                shareId: "shareId",
            });
        }).rejects.toThrow(CloudPDF.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/tenants/tenantId/shares/shareId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shares.update({
                tenantId: "tenantId",
                shareId: "shareId",
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });
});
