// This file was auto-generated by Fern from our API Definition.

import * as CloudPDF from "../../src/api/index";
import { CloudPDFClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TokensClient", () => {
    test("issue (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "doc", sub: "sub", docId: "docId", scope: ["scope"], expiresIn: 1 };
        const rawResponseBody = { token: "token", jti: "jti", expiresAt: 1.1 };

        server
            .mockEndpoint()
            .post("/v1/tenants/tenantId/tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tokens.issue({
            tenantId: "tenantId",
            body: {
                kind: "doc",
                sub: "sub",
                docId: "docId",
                scope: ["scope"],
                expiresIn: 1,
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("issue (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "doc", sub: "x", docId: "docId", scope: ["scope", "scope"], expiresIn: 7776000 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/tenants/tenantId/tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tokens.issue({
                tenantId: "tenantId",
                body: {
                    kind: "doc",
                    sub: "x",
                    docId: "docId",
                    scope: ["scope", "scope"],
                    expiresIn: 7776000,
                },
            });
        }).rejects.toThrow(CloudPDF.BadRequestError);
    });

    test("issue (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "doc", sub: "x", docId: "docId", scope: ["scope", "scope"], expiresIn: 7776000 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/tenants/tenantId/tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tokens.issue({
                tenantId: "tenantId",
                body: {
                    kind: "doc",
                    sub: "x",
                    docId: "docId",
                    scope: ["scope", "scope"],
                    expiresIn: 7776000,
                },
            });
        }).rejects.toThrow(CloudPDF.ForbiddenError);
    });

    test("issue (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "doc", sub: "x", docId: "docId", scope: ["scope", "scope"], expiresIn: 7776000 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/tenants/tenantId/tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tokens.issue({
                tenantId: "tenantId",
                body: {
                    kind: "doc",
                    sub: "x",
                    docId: "docId",
                    scope: ["scope", "scope"],
                    expiresIn: 7776000,
                },
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });

    test("revoke (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};

        server
            .mockEndpoint()
            .post("/v1/tenants/tenantId/tokens/jti/revoke")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.tokens.revoke({
            tenantId: "tenantId",
            jti: "jti",
        });
        expect(response).toEqual(undefined);
    });

    test("revoke (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/tenants/tenantId/tokens/jti/revoke")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tokens.revoke({
                tenantId: "tenantId",
                jti: "jti",
            });
        }).rejects.toThrow(CloudPDF.BadRequestError);
    });
});
