// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../../../core/requestBody.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as CloudPDF from "../../../../../index.js";

export declare namespace AnnotationsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class AnnotationsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AnnotationsClient.Options>;

    constructor(options: AnnotationsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {CloudPDF.doc.ListAnnotationsRequest} request
     * @param {AnnotationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudPDF.NotFoundError}
     * @throws {@link errors.CloudPDFError}
     * @throws {@link errors.CloudPDFTimeoutError}
     *
     * @example
     *     await client.doc.annotations.list({
     *         docId: "docId",
     *         layerName: "layerName",
     *         pon: 1
     *     })
     */
    public list(
        request: CloudPDF.doc.ListAnnotationsRequest,
        requestOptions?: AnnotationsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudPDF.DocAnnotationsList200Response> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: CloudPDF.doc.ListAnnotationsRequest,
        requestOptions?: AnnotationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudPDF.DocAnnotationsList200Response>> {
        const { docId, layerName, pon, "X-Document-Password": documentPassword } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Document-Password": documentPassword }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/docs/${core.url.encodePathParam(docId)}/layers/${core.url.encodePathParam(layerName)}/annotations/pages/${core.url.encodePathParam(pon)}/items`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudPDF.DocAnnotationsList200Response,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new CloudPDF.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudPDFError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/docs/{docId}/layers/{layerName}/annotations/pages/{pon}/items",
        );
    }

    /**
     * Doc JWTs may instead carry collab scopes (annotations:create:self, …) that refine per-annotation authorship rules; the API token is exempt from both.
     *
     * @param {CloudPDF.doc.CreateAnnotationsRequest} request
     * @param {AnnotationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudPDF.BadRequestError}
     * @throws {@link CloudPDF.NotFoundError}
     * @throws {@link errors.CloudPDFError}
     * @throws {@link errors.CloudPDFTimeoutError}
     *
     * @example
     *     await client.doc.annotations.create({
     *         docId: "docId",
     *         layerName: "layerName",
     *         pon: 1,
     *         body: {
     *             "key": "value"
     *         }
     *     })
     */
    public create(
        request: CloudPDF.doc.CreateAnnotationsRequest,
        requestOptions?: AnnotationsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudPDF.DocAnnotationsCreate200Response> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: CloudPDF.doc.CreateAnnotationsRequest,
        requestOptions?: AnnotationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudPDF.DocAnnotationsCreate200Response>> {
        const { docId, layerName, pon, "X-Document-Password": documentPassword, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Document-Password": documentPassword }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/docs/${core.url.encodePathParam(docId)}/layers/${core.url.encodePathParam(layerName)}/annotations/pages/${core.url.encodePathParam(pon)}/items`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudPDF.DocAnnotationsCreate200Response,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudPDF.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new CloudPDF.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudPDFError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/docs/{docId}/layers/{layerName}/annotations/pages/{pon}/items",
        );
    }

    /**
     * @param {CloudPDF.doc.DeleteAnnotationsRequest} request
     * @param {AnnotationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudPDF.NotFoundError}
     * @throws {@link errors.CloudPDFError}
     * @throws {@link errors.CloudPDFTimeoutError}
     *
     * @example
     *     await client.doc.annotations.delete({
     *         docId: "docId",
     *         layerName: "layerName",
     *         pon: 1,
     *         annotKey: "annotKey"
     *     })
     */
    public delete(
        request: CloudPDF.doc.DeleteAnnotationsRequest,
        requestOptions?: AnnotationsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudPDF.DocAnnotationsDelete200Response> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: CloudPDF.doc.DeleteAnnotationsRequest,
        requestOptions?: AnnotationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudPDF.DocAnnotationsDelete200Response>> {
        const { docId, layerName, pon, annotKey, "X-Document-Password": documentPassword } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Document-Password": documentPassword }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/docs/${core.url.encodePathParam(docId)}/layers/${core.url.encodePathParam(layerName)}/annotations/pages/${core.url.encodePathParam(pon)}/items/${core.url.encodePathParam(annotKey)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudPDF.DocAnnotationsDelete200Response,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new CloudPDF.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudPDFError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/v1/docs/{docId}/layers/{layerName}/annotations/pages/{pon}/items/{annotKey}",
        );
    }

    /**
     * @param {CloudPDF.doc.UpdateAnnotationsRequest} request
     * @param {AnnotationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudPDF.BadRequestError}
     * @throws {@link CloudPDF.NotFoundError}
     * @throws {@link errors.CloudPDFError}
     * @throws {@link errors.CloudPDFTimeoutError}
     *
     * @example
     *     await client.doc.annotations.update({
     *         docId: "docId",
     *         layerName: "layerName",
     *         pon: 1,
     *         annotKey: "annotKey",
     *         body: {
     *             "key": "value"
     *         }
     *     })
     */
    public update(
        request: CloudPDF.doc.UpdateAnnotationsRequest,
        requestOptions?: AnnotationsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudPDF.DocAnnotationsUpdate200Response> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: CloudPDF.doc.UpdateAnnotationsRequest,
        requestOptions?: AnnotationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudPDF.DocAnnotationsUpdate200Response>> {
        const { docId, layerName, pon, annotKey, "X-Document-Password": documentPassword, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Document-Password": documentPassword }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/docs/${core.url.encodePathParam(docId)}/layers/${core.url.encodePathParam(layerName)}/annotations/pages/${core.url.encodePathParam(pon)}/items/${core.url.encodePathParam(annotKey)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudPDF.DocAnnotationsUpdate200Response,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudPDF.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new CloudPDF.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudPDFError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/v1/docs/{docId}/layers/{layerName}/annotations/pages/{pon}/items/{annotKey}",
        );
    }
}
