// This file was auto-generated by Fern from our API Definition.

export interface AdminErrorPayload {
    error: AdminErrorPayload.Error_;
}

export namespace AdminErrorPayload {
    export interface Error_ {
        code: string;
        message: string;
    }
}
