// This file was auto-generated by Fern from our API Definition.

export interface DeploymentLicenseStatusResponse {
    license?: unknown | undefined;
    reporting?: (unknown | null) | undefined;
    usage?: (unknown | null) | undefined;
}
