// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRef =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRef.ObjectNumber
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRef.Nm
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRef.Index;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRefIndex.Revision;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRefIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
