// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygonInReplyTo =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygonInReplyTo.ObjectNumber
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygonInReplyTo.Nm
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygonInReplyTo.Index;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygonInReplyTo {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygonInReplyToIndex.Revision;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygonInReplyToIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
