// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightRef =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightRef.ObjectNumber
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightRef.Nm
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightRef.Index;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightRefIndex.Revision;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightRefIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
