// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemUnderlineInReplyTo =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnderlineInReplyTo.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnderlineInReplyTo.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnderlineInReplyTo.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemUnderlineInReplyTo {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemUnderlineInReplyToIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemUnderlineInReplyToIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
