// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemSquigglyRef =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyRef.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyRef.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyRef.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemSquigglyRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemSquigglyRefIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemSquigglyRefIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
