// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemCaretRef =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretRef.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretRef.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretRef.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemCaretRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemCaretRefIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemCaretRefIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
