// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemStampRef =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampRef.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampRef.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampRef.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemStampRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemStampRefIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemStampRefIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
