// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemPageStateWeakAnnotationState =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemPageStateWeakAnnotationState.Unknown
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemPageStateWeakAnnotationState.Known;

export namespace DocAnnotationsListAll200ResponsePagesItemPageStateWeakAnnotationState {
    export interface Unknown {
        kind: "unknown";
    }

    export interface Known {
        kind: "known";
        hasAnyWeakAnnotations: boolean;
    }
}
