// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTarget =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTarget.Goto
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTarget.Uri
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTarget.GotoRemote
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTarget.Launch
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTarget.Javascript
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTarget.Named
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTarget.Unsupported;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTarget {
    export interface Goto {
        kind: "goto";
        destination: CloudPDF.PdfDestination;
    }

    export interface Uri {
        kind: "uri";
        uri: string;
    }

    export interface GotoRemote {
        kind: "goto-remote";
        file: string;
    }

    export interface Launch {
        kind: "launch";
        path: string;
    }

    export interface Javascript {
        kind: "javascript";
    }

    export interface Named {
        kind: "named";
        name: string;
    }

    export interface Unsupported {
        kind: "unsupported";
    }
}
