// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareRef =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareRef.ObjectNumber
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareRef.Nm
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareRef.Index;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareRefIndex.Revision;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareRefIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
