// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemWidgetInReplyTo =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetInReplyTo.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetInReplyTo.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetInReplyTo.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemWidgetInReplyTo {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemWidgetInReplyToIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemWidgetInReplyToIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
