// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemFreeTextRef =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemFreeTextRef.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemFreeTextRef.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemFreeTextRef.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemFreeTextRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemFreeTextRefIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemFreeTextRefIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
