// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemPolygonInReplyTo =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonInReplyTo.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonInReplyTo.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonInReplyTo.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemPolygonInReplyTo {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemPolygonInReplyToIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemPolygonInReplyToIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
