// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemStrikeoutRef =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStrikeoutRef.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStrikeoutRef.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStrikeoutRef.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemStrikeoutRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemStrikeoutRefIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemStrikeoutRefIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
