// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretInReplyTo =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretInReplyTo.ObjectNumber
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretInReplyTo.Nm
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretInReplyTo.Index;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretInReplyTo {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretInReplyToIndex.Revision;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretInReplyToIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
