// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemTextRef =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemTextRef.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemTextRef.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemTextRef.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemTextRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemTextRefIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemTextRefIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
