// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineRef =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineRef.ObjectNumber
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineRef.Nm
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineRef.Index;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineRefIndex.Revision;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineRefIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
