// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemSquigglyInReplyTo =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyInReplyTo.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyInReplyTo.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyInReplyTo.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemSquigglyInReplyTo {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemSquigglyInReplyToIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemSquigglyInReplyToIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
