// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemRedactInReplyTo =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemRedactInReplyTo.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemRedactInReplyTo.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemRedactInReplyTo.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemRedactInReplyTo {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemRedactInReplyToIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemRedactInReplyToIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
