// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemLinkTarget =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkTarget.Goto
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkTarget.Uri
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkTarget.GotoRemote
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkTarget.Launch
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkTarget.Javascript
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkTarget.Named
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkTarget.Unsupported;

export namespace DocAnnotationsList200ResponseAnnotationsItemLinkTarget {
    export interface Goto {
        kind: "goto";
        destination: CloudPDF.PdfDestination;
    }

    export interface Uri {
        kind: "uri";
        uri: string;
    }

    export interface GotoRemote {
        kind: "goto-remote";
        file: string;
    }

    export interface Launch {
        kind: "launch";
        path: string;
    }

    export interface Javascript {
        kind: "javascript";
    }

    export interface Named {
        kind: "named";
        name: string;
    }

    export interface Unsupported {
        kind: "unsupported";
    }
}
