// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemCaretInReplyTo =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretInReplyTo.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretInReplyTo.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretInReplyTo.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemCaretInReplyTo {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemCaretInReplyToIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemCaretInReplyToIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
