// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemLinkInReplyTo =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkInReplyTo.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkInReplyTo.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkInReplyTo.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemLinkInReplyTo {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemLinkInReplyToIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemLinkInReplyToIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
