// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemLinkRef =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkRef.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkRef.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkRef.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemLinkRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemLinkRefIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemLinkRefIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
