// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItem =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItem.Highlight
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItem.Underline
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItem.Squiggly
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItem.Strikeout
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItem.Circle
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItem.Square
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItem.Polygon
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItem.Polyline
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItem.Line
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItem.Link
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItem.Ink
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItem.FreeText
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItem.Caret
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItem.Text
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItem.Stamp
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItem.FileAttachment
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItem.Widget
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItem.Redact
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItem.Unsupported;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItem {
    export interface Highlight {
        subtype: "highlight";
        ref: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightRef;
        pageObjectNumber: number;
        index: number;
        identityQuality: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlight.IdentityQuality;
        nm: string | null;
        flags: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlight.Flags;
        rect: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlight.Rect;
        contents: string | null;
        subject: string | null;
        author: string | null;
        created: string | null;
        modified: string | null;
        blendMode: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlight.BlendMode;
        inReplyTo: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightInReplyTo | null;
        replyType: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlight.ReplyType | null;
        userId?: string | undefined;
        groupId?: string | undefined;
        createdBy?: string | undefined;
        updatedBy?: string | undefined;
        actions?: CloudPDF.PdfAnnotationActions | undefined;
        color: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlight.Color;
        opacity: number;
        quadPoints: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlight.QuadPoints.Item[];
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlight {
        export const IdentityQuality = {
            Durable: "durable",
            Weak: "weak",
        } as const;
        export type IdentityQuality = (typeof IdentityQuality)[keyof typeof IdentityQuality];

        export interface Flags {
            invisible: boolean;
            hidden: boolean;
            print: boolean;
            noZoom: boolean;
            noRotate: boolean;
            noView: boolean;
            readOnly: boolean;
            locked: boolean;
            toggleNoView: boolean;
            lockedContents: boolean;
        }

        export interface Rect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }

        export const BlendMode = {
            Normal: "normal",
            Multiply: "multiply",
            Screen: "screen",
            Overlay: "overlay",
            Darken: "darken",
            Lighten: "lighten",
            ColorDodge: "color-dodge",
            ColorBurn: "color-burn",
            HardLight: "hard-light",
            SoftLight: "soft-light",
            Difference: "difference",
            Exclusion: "exclusion",
            Hue: "hue",
            Saturation: "saturation",
            Color: "color",
            Luminosity: "luminosity",
        } as const;
        export type BlendMode = (typeof BlendMode)[keyof typeof BlendMode];
        export const ReplyType = {
            Reply: "reply",
            Group: "group",
        } as const;
        export type ReplyType = (typeof ReplyType)[keyof typeof ReplyType];

        export interface Color {
            r: number;
            g: number;
            b: number;
        }

        export type QuadPoints = QuadPoints.Item[];

        export namespace QuadPoints {
            export interface Item {
                p1: Item.P1;
                p2: Item.P2;
                p3: Item.P3;
                p4: Item.P4;
            }

            export namespace Item {
                export interface P1 {
                    x: number;
                    y: number;
                }

                export interface P2 {
                    x: number;
                    y: number;
                }

                export interface P3 {
                    x: number;
                    y: number;
                }

                export interface P4 {
                    x: number;
                    y: number;
                }
            }
        }
    }

    export interface Underline {
        subtype: "underline";
        ref: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineRef;
        pageObjectNumber: number;
        index: number;
        identityQuality: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderline.IdentityQuality;
        nm: string | null;
        flags: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderline.Flags;
        rect: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderline.Rect;
        contents: string | null;
        subject: string | null;
        author: string | null;
        created: string | null;
        modified: string | null;
        blendMode: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderline.BlendMode;
        inReplyTo: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineInReplyTo | null;
        replyType: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderline.ReplyType | null;
        userId?: string | undefined;
        groupId?: string | undefined;
        createdBy?: string | undefined;
        updatedBy?: string | undefined;
        actions?: CloudPDF.PdfAnnotationActions | undefined;
        color: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderline.Color;
        opacity: number;
        quadPoints: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderline.QuadPoints.Item[];
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderline {
        export const IdentityQuality = {
            Durable: "durable",
            Weak: "weak",
        } as const;
        export type IdentityQuality = (typeof IdentityQuality)[keyof typeof IdentityQuality];

        export interface Flags {
            invisible: boolean;
            hidden: boolean;
            print: boolean;
            noZoom: boolean;
            noRotate: boolean;
            noView: boolean;
            readOnly: boolean;
            locked: boolean;
            toggleNoView: boolean;
            lockedContents: boolean;
        }

        export interface Rect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }

        export const BlendMode = {
            Normal: "normal",
            Multiply: "multiply",
            Screen: "screen",
            Overlay: "overlay",
            Darken: "darken",
            Lighten: "lighten",
            ColorDodge: "color-dodge",
            ColorBurn: "color-burn",
            HardLight: "hard-light",
            SoftLight: "soft-light",
            Difference: "difference",
            Exclusion: "exclusion",
            Hue: "hue",
            Saturation: "saturation",
            Color: "color",
            Luminosity: "luminosity",
        } as const;
        export type BlendMode = (typeof BlendMode)[keyof typeof BlendMode];
        export const ReplyType = {
            Reply: "reply",
            Group: "group",
        } as const;
        export type ReplyType = (typeof ReplyType)[keyof typeof ReplyType];

        export interface Color {
            r: number;
            g: number;
            b: number;
        }

        export type QuadPoints = QuadPoints.Item[];

        export namespace QuadPoints {
            export interface Item {
                p1: Item.P1;
                p2: Item.P2;
                p3: Item.P3;
                p4: Item.P4;
            }

            export namespace Item {
                export interface P1 {
                    x: number;
                    y: number;
                }

                export interface P2 {
                    x: number;
                    y: number;
                }

                export interface P3 {
                    x: number;
                    y: number;
                }

                export interface P4 {
                    x: number;
                    y: number;
                }
            }
        }
    }

    export interface Squiggly {
        subtype: "squiggly";
        ref: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyRef;
        pageObjectNumber: number;
        index: number;
        identityQuality: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquiggly.IdentityQuality;
        nm: string | null;
        flags: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquiggly.Flags;
        rect: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquiggly.Rect;
        contents: string | null;
        subject: string | null;
        author: string | null;
        created: string | null;
        modified: string | null;
        blendMode: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquiggly.BlendMode;
        inReplyTo: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyInReplyTo | null;
        replyType: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquiggly.ReplyType | null;
        userId?: string | undefined;
        groupId?: string | undefined;
        createdBy?: string | undefined;
        updatedBy?: string | undefined;
        actions?: CloudPDF.PdfAnnotationActions | undefined;
        color: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquiggly.Color;
        opacity: number;
        quadPoints: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquiggly.QuadPoints.Item[];
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquiggly {
        export const IdentityQuality = {
            Durable: "durable",
            Weak: "weak",
        } as const;
        export type IdentityQuality = (typeof IdentityQuality)[keyof typeof IdentityQuality];

        export interface Flags {
            invisible: boolean;
            hidden: boolean;
            print: boolean;
            noZoom: boolean;
            noRotate: boolean;
            noView: boolean;
            readOnly: boolean;
            locked: boolean;
            toggleNoView: boolean;
            lockedContents: boolean;
        }

        export interface Rect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }

        export const BlendMode = {
            Normal: "normal",
            Multiply: "multiply",
            Screen: "screen",
            Overlay: "overlay",
            Darken: "darken",
            Lighten: "lighten",
            ColorDodge: "color-dodge",
            ColorBurn: "color-burn",
            HardLight: "hard-light",
            SoftLight: "soft-light",
            Difference: "difference",
            Exclusion: "exclusion",
            Hue: "hue",
            Saturation: "saturation",
            Color: "color",
            Luminosity: "luminosity",
        } as const;
        export type BlendMode = (typeof BlendMode)[keyof typeof BlendMode];
        export const ReplyType = {
            Reply: "reply",
            Group: "group",
        } as const;
        export type ReplyType = (typeof ReplyType)[keyof typeof ReplyType];

        export interface Color {
            r: number;
            g: number;
            b: number;
        }

        export type QuadPoints = QuadPoints.Item[];

        export namespace QuadPoints {
            export interface Item {
                p1: Item.P1;
                p2: Item.P2;
                p3: Item.P3;
                p4: Item.P4;
            }

            export namespace Item {
                export interface P1 {
                    x: number;
                    y: number;
                }

                export interface P2 {
                    x: number;
                    y: number;
                }

                export interface P3 {
                    x: number;
                    y: number;
                }

                export interface P4 {
                    x: number;
                    y: number;
                }
            }
        }
    }

    export interface Strikeout {
        subtype: "strikeout";
        ref: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutRef;
        pageObjectNumber: number;
        index: number;
        identityQuality: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeout.IdentityQuality;
        nm: string | null;
        flags: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeout.Flags;
        rect: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeout.Rect;
        contents: string | null;
        subject: string | null;
        author: string | null;
        created: string | null;
        modified: string | null;
        blendMode: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeout.BlendMode;
        inReplyTo: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutInReplyTo | null;
        replyType: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeout.ReplyType | null;
        userId?: string | undefined;
        groupId?: string | undefined;
        createdBy?: string | undefined;
        updatedBy?: string | undefined;
        actions?: CloudPDF.PdfAnnotationActions | undefined;
        color: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeout.Color;
        opacity: number;
        quadPoints: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeout.QuadPoints.Item[];
        intent: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeout.Intent | null;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeout {
        export const IdentityQuality = {
            Durable: "durable",
            Weak: "weak",
        } as const;
        export type IdentityQuality = (typeof IdentityQuality)[keyof typeof IdentityQuality];

        export interface Flags {
            invisible: boolean;
            hidden: boolean;
            print: boolean;
            noZoom: boolean;
            noRotate: boolean;
            noView: boolean;
            readOnly: boolean;
            locked: boolean;
            toggleNoView: boolean;
            lockedContents: boolean;
        }

        export interface Rect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }

        export const BlendMode = {
            Normal: "normal",
            Multiply: "multiply",
            Screen: "screen",
            Overlay: "overlay",
            Darken: "darken",
            Lighten: "lighten",
            ColorDodge: "color-dodge",
            ColorBurn: "color-burn",
            HardLight: "hard-light",
            SoftLight: "soft-light",
            Difference: "difference",
            Exclusion: "exclusion",
            Hue: "hue",
            Saturation: "saturation",
            Color: "color",
            Luminosity: "luminosity",
        } as const;
        export type BlendMode = (typeof BlendMode)[keyof typeof BlendMode];
        export const ReplyType = {
            Reply: "reply",
            Group: "group",
        } as const;
        export type ReplyType = (typeof ReplyType)[keyof typeof ReplyType];

        export interface Color {
            r: number;
            g: number;
            b: number;
        }

        export type QuadPoints = QuadPoints.Item[];

        export namespace QuadPoints {
            export interface Item {
                p1: Item.P1;
                p2: Item.P2;
                p3: Item.P3;
                p4: Item.P4;
            }

            export namespace Item {
                export interface P1 {
                    x: number;
                    y: number;
                }

                export interface P2 {
                    x: number;
                    y: number;
                }

                export interface P3 {
                    x: number;
                    y: number;
                }

                export interface P4 {
                    x: number;
                    y: number;
                }
            }
        }

        export const Intent = {
            StrikeoutTextEdit: "strikeout-text-edit",
        } as const;
        export type Intent = (typeof Intent)[keyof typeof Intent];
    }

    export interface Circle {
        subtype: "circle";
        ref: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleRef;
        pageObjectNumber: number;
        index: number;
        identityQuality: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircle.IdentityQuality;
        nm: string | null;
        flags: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircle.Flags;
        rect: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircle.Rect;
        contents: string | null;
        subject: string | null;
        author: string | null;
        created: string | null;
        modified: string | null;
        blendMode: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircle.BlendMode;
        inReplyTo: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleInReplyTo | null;
        replyType: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircle.ReplyType | null;
        userId?: string | undefined;
        groupId?: string | undefined;
        createdBy?: string | undefined;
        updatedBy?: string | undefined;
        actions?: CloudPDF.PdfAnnotationActions | undefined;
        color: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircle.Color;
        opacity: number;
        strokeWidth: number;
        borderStyle: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircle.BorderStyle;
        dashArray?: number[] | undefined;
        interiorColor: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircle.InteriorColor | null;
        cloudyIntensity: number | null;
        rectDifferences: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircle.RectDifferences | null;
        rotation?: number | undefined;
        unrotatedRect?: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircle.UnrotatedRect | undefined;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircle {
        export const IdentityQuality = {
            Durable: "durable",
            Weak: "weak",
        } as const;
        export type IdentityQuality = (typeof IdentityQuality)[keyof typeof IdentityQuality];

        export interface Flags {
            invisible: boolean;
            hidden: boolean;
            print: boolean;
            noZoom: boolean;
            noRotate: boolean;
            noView: boolean;
            readOnly: boolean;
            locked: boolean;
            toggleNoView: boolean;
            lockedContents: boolean;
        }

        export interface Rect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }

        export const BlendMode = {
            Normal: "normal",
            Multiply: "multiply",
            Screen: "screen",
            Overlay: "overlay",
            Darken: "darken",
            Lighten: "lighten",
            ColorDodge: "color-dodge",
            ColorBurn: "color-burn",
            HardLight: "hard-light",
            SoftLight: "soft-light",
            Difference: "difference",
            Exclusion: "exclusion",
            Hue: "hue",
            Saturation: "saturation",
            Color: "color",
            Luminosity: "luminosity",
        } as const;
        export type BlendMode = (typeof BlendMode)[keyof typeof BlendMode];
        export const ReplyType = {
            Reply: "reply",
            Group: "group",
        } as const;
        export type ReplyType = (typeof ReplyType)[keyof typeof ReplyType];

        export interface Color {
            r: number;
            g: number;
            b: number;
        }

        export const BorderStyle = {
            Solid: "solid",
            Dashed: "dashed",
            Beveled: "beveled",
            Inset: "inset",
        } as const;
        export type BorderStyle = (typeof BorderStyle)[keyof typeof BorderStyle];

        export interface InteriorColor {
            r: number;
            g: number;
            b: number;
        }

        export interface RectDifferences {
            left: number;
            top: number;
            right: number;
            bottom: number;
        }

        export interface UnrotatedRect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }
    }

    export interface Square {
        subtype: "square";
        ref: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareRef;
        pageObjectNumber: number;
        index: number;
        identityQuality: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquare.IdentityQuality;
        nm: string | null;
        flags: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquare.Flags;
        rect: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquare.Rect;
        contents: string | null;
        subject: string | null;
        author: string | null;
        created: string | null;
        modified: string | null;
        blendMode: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquare.BlendMode;
        inReplyTo: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareInReplyTo | null;
        replyType: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquare.ReplyType | null;
        userId?: string | undefined;
        groupId?: string | undefined;
        createdBy?: string | undefined;
        updatedBy?: string | undefined;
        actions?: CloudPDF.PdfAnnotationActions | undefined;
        color: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquare.Color;
        opacity: number;
        strokeWidth: number;
        borderStyle: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquare.BorderStyle;
        dashArray?: number[] | undefined;
        interiorColor: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquare.InteriorColor | null;
        cloudyIntensity: number | null;
        rectDifferences: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquare.RectDifferences | null;
        rotation?: number | undefined;
        unrotatedRect?: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquare.UnrotatedRect | undefined;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquare {
        export const IdentityQuality = {
            Durable: "durable",
            Weak: "weak",
        } as const;
        export type IdentityQuality = (typeof IdentityQuality)[keyof typeof IdentityQuality];

        export interface Flags {
            invisible: boolean;
            hidden: boolean;
            print: boolean;
            noZoom: boolean;
            noRotate: boolean;
            noView: boolean;
            readOnly: boolean;
            locked: boolean;
            toggleNoView: boolean;
            lockedContents: boolean;
        }

        export interface Rect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }

        export const BlendMode = {
            Normal: "normal",
            Multiply: "multiply",
            Screen: "screen",
            Overlay: "overlay",
            Darken: "darken",
            Lighten: "lighten",
            ColorDodge: "color-dodge",
            ColorBurn: "color-burn",
            HardLight: "hard-light",
            SoftLight: "soft-light",
            Difference: "difference",
            Exclusion: "exclusion",
            Hue: "hue",
            Saturation: "saturation",
            Color: "color",
            Luminosity: "luminosity",
        } as const;
        export type BlendMode = (typeof BlendMode)[keyof typeof BlendMode];
        export const ReplyType = {
            Reply: "reply",
            Group: "group",
        } as const;
        export type ReplyType = (typeof ReplyType)[keyof typeof ReplyType];

        export interface Color {
            r: number;
            g: number;
            b: number;
        }

        export const BorderStyle = {
            Solid: "solid",
            Dashed: "dashed",
            Beveled: "beveled",
            Inset: "inset",
        } as const;
        export type BorderStyle = (typeof BorderStyle)[keyof typeof BorderStyle];

        export interface InteriorColor {
            r: number;
            g: number;
            b: number;
        }

        export interface RectDifferences {
            left: number;
            top: number;
            right: number;
            bottom: number;
        }

        export interface UnrotatedRect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }
    }

    export interface Polygon {
        subtype: "polygon";
        ref: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygonRef;
        pageObjectNumber: number;
        index: number;
        identityQuality: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygon.IdentityQuality;
        nm: string | null;
        flags: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygon.Flags;
        rect: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygon.Rect;
        contents: string | null;
        subject: string | null;
        author: string | null;
        created: string | null;
        modified: string | null;
        blendMode: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygon.BlendMode;
        inReplyTo: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygonInReplyTo | null;
        replyType: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygon.ReplyType | null;
        userId?: string | undefined;
        groupId?: string | undefined;
        createdBy?: string | undefined;
        updatedBy?: string | undefined;
        actions?: CloudPDF.PdfAnnotationActions | undefined;
        color: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygon.Color;
        opacity: number;
        strokeWidth: number;
        borderStyle: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygon.BorderStyle;
        dashArray?: number[] | undefined;
        interiorColor: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygon.InteriorColor | null;
        vertices: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygon.Vertices.Item[];
        rotation?: number | undefined;
        cloudyIntensity: number | null;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygon {
        export const IdentityQuality = {
            Durable: "durable",
            Weak: "weak",
        } as const;
        export type IdentityQuality = (typeof IdentityQuality)[keyof typeof IdentityQuality];

        export interface Flags {
            invisible: boolean;
            hidden: boolean;
            print: boolean;
            noZoom: boolean;
            noRotate: boolean;
            noView: boolean;
            readOnly: boolean;
            locked: boolean;
            toggleNoView: boolean;
            lockedContents: boolean;
        }

        export interface Rect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }

        export const BlendMode = {
            Normal: "normal",
            Multiply: "multiply",
            Screen: "screen",
            Overlay: "overlay",
            Darken: "darken",
            Lighten: "lighten",
            ColorDodge: "color-dodge",
            ColorBurn: "color-burn",
            HardLight: "hard-light",
            SoftLight: "soft-light",
            Difference: "difference",
            Exclusion: "exclusion",
            Hue: "hue",
            Saturation: "saturation",
            Color: "color",
            Luminosity: "luminosity",
        } as const;
        export type BlendMode = (typeof BlendMode)[keyof typeof BlendMode];
        export const ReplyType = {
            Reply: "reply",
            Group: "group",
        } as const;
        export type ReplyType = (typeof ReplyType)[keyof typeof ReplyType];

        export interface Color {
            r: number;
            g: number;
            b: number;
        }

        export const BorderStyle = {
            Solid: "solid",
            Dashed: "dashed",
            Beveled: "beveled",
            Inset: "inset",
        } as const;
        export type BorderStyle = (typeof BorderStyle)[keyof typeof BorderStyle];

        export interface InteriorColor {
            r: number;
            g: number;
            b: number;
        }

        export type Vertices = Vertices.Item[];

        export namespace Vertices {
            export interface Item {
                x: number;
                y: number;
            }
        }
    }

    export interface Polyline {
        subtype: "polyline";
        ref: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineRef;
        pageObjectNumber: number;
        index: number;
        identityQuality: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolyline.IdentityQuality;
        nm: string | null;
        flags: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolyline.Flags;
        rect: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolyline.Rect;
        contents: string | null;
        subject: string | null;
        author: string | null;
        created: string | null;
        modified: string | null;
        blendMode: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolyline.BlendMode;
        inReplyTo: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineInReplyTo | null;
        replyType: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolyline.ReplyType | null;
        userId?: string | undefined;
        groupId?: string | undefined;
        createdBy?: string | undefined;
        updatedBy?: string | undefined;
        actions?: CloudPDF.PdfAnnotationActions | undefined;
        color: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolyline.Color;
        opacity: number;
        strokeWidth: number;
        borderStyle: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolyline.BorderStyle;
        dashArray?: number[] | undefined;
        interiorColor: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolyline.InteriorColor | null;
        vertices: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolyline.Vertices.Item[];
        rotation?: number | undefined;
        lineEndings: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolyline.LineEndings;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolyline {
        export const IdentityQuality = {
            Durable: "durable",
            Weak: "weak",
        } as const;
        export type IdentityQuality = (typeof IdentityQuality)[keyof typeof IdentityQuality];

        export interface Flags {
            invisible: boolean;
            hidden: boolean;
            print: boolean;
            noZoom: boolean;
            noRotate: boolean;
            noView: boolean;
            readOnly: boolean;
            locked: boolean;
            toggleNoView: boolean;
            lockedContents: boolean;
        }

        export interface Rect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }

        export const BlendMode = {
            Normal: "normal",
            Multiply: "multiply",
            Screen: "screen",
            Overlay: "overlay",
            Darken: "darken",
            Lighten: "lighten",
            ColorDodge: "color-dodge",
            ColorBurn: "color-burn",
            HardLight: "hard-light",
            SoftLight: "soft-light",
            Difference: "difference",
            Exclusion: "exclusion",
            Hue: "hue",
            Saturation: "saturation",
            Color: "color",
            Luminosity: "luminosity",
        } as const;
        export type BlendMode = (typeof BlendMode)[keyof typeof BlendMode];
        export const ReplyType = {
            Reply: "reply",
            Group: "group",
        } as const;
        export type ReplyType = (typeof ReplyType)[keyof typeof ReplyType];

        export interface Color {
            r: number;
            g: number;
            b: number;
        }

        export const BorderStyle = {
            Solid: "solid",
            Dashed: "dashed",
            Beveled: "beveled",
            Inset: "inset",
        } as const;
        export type BorderStyle = (typeof BorderStyle)[keyof typeof BorderStyle];

        export interface InteriorColor {
            r: number;
            g: number;
            b: number;
        }

        export type Vertices = Vertices.Item[];

        export namespace Vertices {
            export interface Item {
                x: number;
                y: number;
            }
        }

        export interface LineEndings {
            start: LineEndings.Start;
            end: LineEndings.End;
        }

        export namespace LineEndings {
            export const Start = {
                None: "none",
                Square: "square",
                Circle: "circle",
                Diamond: "diamond",
                OpenArrow: "open-arrow",
                ClosedArrow: "closed-arrow",
                Butt: "butt",
                ROpenArrow: "r-open-arrow",
                RClosedArrow: "r-closed-arrow",
                Slash: "slash",
            } as const;
            export type Start = (typeof Start)[keyof typeof Start];
            export const End = {
                None: "none",
                Square: "square",
                Circle: "circle",
                Diamond: "diamond",
                OpenArrow: "open-arrow",
                ClosedArrow: "closed-arrow",
                Butt: "butt",
                ROpenArrow: "r-open-arrow",
                RClosedArrow: "r-closed-arrow",
                Slash: "slash",
            } as const;
            export type End = (typeof End)[keyof typeof End];
        }
    }

    export interface Line {
        subtype: "line";
        ref: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineRef;
        pageObjectNumber: number;
        index: number;
        identityQuality: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLine.IdentityQuality;
        nm: string | null;
        flags: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLine.Flags;
        rect: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLine.Rect;
        contents: string | null;
        subject: string | null;
        author: string | null;
        created: string | null;
        modified: string | null;
        blendMode: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLine.BlendMode;
        inReplyTo: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineInReplyTo | null;
        replyType: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLine.ReplyType | null;
        userId?: string | undefined;
        groupId?: string | undefined;
        createdBy?: string | undefined;
        updatedBy?: string | undefined;
        actions?: CloudPDF.PdfAnnotationActions | undefined;
        color: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLine.Color;
        opacity: number;
        strokeWidth: number;
        borderStyle: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLine.BorderStyle;
        dashArray?: number[] | undefined;
        interiorColor: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLine.InteriorColor | null;
        linePoints: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLine.LinePoints;
        lineEndings: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLine.LineEndings;
        rotation?: number | undefined;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLine {
        export const IdentityQuality = {
            Durable: "durable",
            Weak: "weak",
        } as const;
        export type IdentityQuality = (typeof IdentityQuality)[keyof typeof IdentityQuality];

        export interface Flags {
            invisible: boolean;
            hidden: boolean;
            print: boolean;
            noZoom: boolean;
            noRotate: boolean;
            noView: boolean;
            readOnly: boolean;
            locked: boolean;
            toggleNoView: boolean;
            lockedContents: boolean;
        }

        export interface Rect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }

        export const BlendMode = {
            Normal: "normal",
            Multiply: "multiply",
            Screen: "screen",
            Overlay: "overlay",
            Darken: "darken",
            Lighten: "lighten",
            ColorDodge: "color-dodge",
            ColorBurn: "color-burn",
            HardLight: "hard-light",
            SoftLight: "soft-light",
            Difference: "difference",
            Exclusion: "exclusion",
            Hue: "hue",
            Saturation: "saturation",
            Color: "color",
            Luminosity: "luminosity",
        } as const;
        export type BlendMode = (typeof BlendMode)[keyof typeof BlendMode];
        export const ReplyType = {
            Reply: "reply",
            Group: "group",
        } as const;
        export type ReplyType = (typeof ReplyType)[keyof typeof ReplyType];

        export interface Color {
            r: number;
            g: number;
            b: number;
        }

        export const BorderStyle = {
            Solid: "solid",
            Dashed: "dashed",
            Beveled: "beveled",
            Inset: "inset",
        } as const;
        export type BorderStyle = (typeof BorderStyle)[keyof typeof BorderStyle];

        export interface InteriorColor {
            r: number;
            g: number;
            b: number;
        }

        export interface LinePoints {
            start: LinePoints.Start;
            end: LinePoints.End;
        }

        export namespace LinePoints {
            export interface Start {
                x: number;
                y: number;
            }

            export interface End {
                x: number;
                y: number;
            }
        }

        export interface LineEndings {
            start: LineEndings.Start;
            end: LineEndings.End;
        }

        export namespace LineEndings {
            export const Start = {
                None: "none",
                Square: "square",
                Circle: "circle",
                Diamond: "diamond",
                OpenArrow: "open-arrow",
                ClosedArrow: "closed-arrow",
                Butt: "butt",
                ROpenArrow: "r-open-arrow",
                RClosedArrow: "r-closed-arrow",
                Slash: "slash",
            } as const;
            export type Start = (typeof Start)[keyof typeof Start];
            export const End = {
                None: "none",
                Square: "square",
                Circle: "circle",
                Diamond: "diamond",
                OpenArrow: "open-arrow",
                ClosedArrow: "closed-arrow",
                Butt: "butt",
                ROpenArrow: "r-open-arrow",
                RClosedArrow: "r-closed-arrow",
                Slash: "slash",
            } as const;
            export type End = (typeof End)[keyof typeof End];
        }
    }

    export interface Link {
        subtype: "link";
        ref: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkRef;
        pageObjectNumber: number;
        index: number;
        identityQuality: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLink.IdentityQuality;
        nm: string | null;
        flags: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLink.Flags;
        rect: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLink.Rect;
        contents: string | null;
        subject: string | null;
        author: string | null;
        created: string | null;
        modified: string | null;
        blendMode: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLink.BlendMode;
        inReplyTo: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkInReplyTo | null;
        replyType: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLink.ReplyType | null;
        userId?: string | undefined;
        groupId?: string | undefined;
        createdBy?: string | undefined;
        updatedBy?: string | undefined;
        actions?: CloudPDF.PdfAnnotationActions | undefined;
        target: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTarget | null;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLink {
        export const IdentityQuality = {
            Durable: "durable",
            Weak: "weak",
        } as const;
        export type IdentityQuality = (typeof IdentityQuality)[keyof typeof IdentityQuality];

        export interface Flags {
            invisible: boolean;
            hidden: boolean;
            print: boolean;
            noZoom: boolean;
            noRotate: boolean;
            noView: boolean;
            readOnly: boolean;
            locked: boolean;
            toggleNoView: boolean;
            lockedContents: boolean;
        }

        export interface Rect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }

        export const BlendMode = {
            Normal: "normal",
            Multiply: "multiply",
            Screen: "screen",
            Overlay: "overlay",
            Darken: "darken",
            Lighten: "lighten",
            ColorDodge: "color-dodge",
            ColorBurn: "color-burn",
            HardLight: "hard-light",
            SoftLight: "soft-light",
            Difference: "difference",
            Exclusion: "exclusion",
            Hue: "hue",
            Saturation: "saturation",
            Color: "color",
            Luminosity: "luminosity",
        } as const;
        export type BlendMode = (typeof BlendMode)[keyof typeof BlendMode];
        export const ReplyType = {
            Reply: "reply",
            Group: "group",
        } as const;
        export type ReplyType = (typeof ReplyType)[keyof typeof ReplyType];
    }

    export interface Ink {
        subtype: "ink";
        ref: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemInkRef;
        pageObjectNumber: number;
        index: number;
        identityQuality: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemInk.IdentityQuality;
        nm: string | null;
        flags: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemInk.Flags;
        rect: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemInk.Rect;
        contents: string | null;
        subject: string | null;
        author: string | null;
        created: string | null;
        modified: string | null;
        blendMode: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemInk.BlendMode;
        inReplyTo: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemInkInReplyTo | null;
        replyType: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemInk.ReplyType | null;
        userId?: string | undefined;
        groupId?: string | undefined;
        createdBy?: string | undefined;
        updatedBy?: string | undefined;
        actions?: CloudPDF.PdfAnnotationActions | undefined;
        color: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemInk.Color;
        opacity: number;
        strokeWidth: number;
        borderStyle: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemInk.BorderStyle;
        dashArray?: number[] | undefined;
        intent: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemInk.Intent | null;
        inkList: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemInk.InkList.Item[][];
        rotation?: number | undefined;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemInk {
        export const IdentityQuality = {
            Durable: "durable",
            Weak: "weak",
        } as const;
        export type IdentityQuality = (typeof IdentityQuality)[keyof typeof IdentityQuality];

        export interface Flags {
            invisible: boolean;
            hidden: boolean;
            print: boolean;
            noZoom: boolean;
            noRotate: boolean;
            noView: boolean;
            readOnly: boolean;
            locked: boolean;
            toggleNoView: boolean;
            lockedContents: boolean;
        }

        export interface Rect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }

        export const BlendMode = {
            Normal: "normal",
            Multiply: "multiply",
            Screen: "screen",
            Overlay: "overlay",
            Darken: "darken",
            Lighten: "lighten",
            ColorDodge: "color-dodge",
            ColorBurn: "color-burn",
            HardLight: "hard-light",
            SoftLight: "soft-light",
            Difference: "difference",
            Exclusion: "exclusion",
            Hue: "hue",
            Saturation: "saturation",
            Color: "color",
            Luminosity: "luminosity",
        } as const;
        export type BlendMode = (typeof BlendMode)[keyof typeof BlendMode];
        export const ReplyType = {
            Reply: "reply",
            Group: "group",
        } as const;
        export type ReplyType = (typeof ReplyType)[keyof typeof ReplyType];

        export interface Color {
            r: number;
            g: number;
            b: number;
        }

        export const BorderStyle = {
            Solid: "solid",
            Dashed: "dashed",
            Beveled: "beveled",
            Inset: "inset",
        } as const;
        export type BorderStyle = (typeof BorderStyle)[keyof typeof BorderStyle];
        export const Intent = {
            InkHighlight: "ink-highlight",
        } as const;
        export type Intent = (typeof Intent)[keyof typeof Intent];
        export type InkList = InkList.Item[];

        export namespace InkList {
            export interface Item {
                x: number;
                y: number;
            }
        }
    }

    export interface FreeText {
        subtype: "free-text";
        ref: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRef;
        pageObjectNumber: number;
        index: number;
        identityQuality: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeText.IdentityQuality;
        nm: string | null;
        flags: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeText.Flags;
        rect: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeText.Rect;
        contents: string | null;
        subject: string | null;
        author: string | null;
        created: string | null;
        modified: string | null;
        blendMode: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeText.BlendMode;
        inReplyTo: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextInReplyTo | null;
        replyType: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeText.ReplyType | null;
        userId?: string | undefined;
        groupId?: string | undefined;
        createdBy?: string | undefined;
        updatedBy?: string | undefined;
        actions?: CloudPDF.PdfAnnotationActions | undefined;
        intent: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeText.Intent;
        fontFamily: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeText.FontFamily;
        fontSize: number;
        textAlign: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeText.TextAlign;
        color: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeText.Color;
        fontColor?: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeText.FontColor | undefined;
        interiorColor: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeText.InteriorColor | null;
        opacity: number;
        strokeWidth: number;
        borderStyle: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeText.BorderStyle;
        dashArray?: number[] | undefined;
        rectDifferences: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeText.RectDifferences | null;
        calloutLine?: unknown[] | undefined;
        lineEnding?: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeText.LineEnding | undefined;
        rotation?: number | undefined;
        unrotatedRect?: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeText.UnrotatedRect | undefined;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeText {
        export const IdentityQuality = {
            Durable: "durable",
            Weak: "weak",
        } as const;
        export type IdentityQuality = (typeof IdentityQuality)[keyof typeof IdentityQuality];

        export interface Flags {
            invisible: boolean;
            hidden: boolean;
            print: boolean;
            noZoom: boolean;
            noRotate: boolean;
            noView: boolean;
            readOnly: boolean;
            locked: boolean;
            toggleNoView: boolean;
            lockedContents: boolean;
        }

        export interface Rect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }

        export const BlendMode = {
            Normal: "normal",
            Multiply: "multiply",
            Screen: "screen",
            Overlay: "overlay",
            Darken: "darken",
            Lighten: "lighten",
            ColorDodge: "color-dodge",
            ColorBurn: "color-burn",
            HardLight: "hard-light",
            SoftLight: "soft-light",
            Difference: "difference",
            Exclusion: "exclusion",
            Hue: "hue",
            Saturation: "saturation",
            Color: "color",
            Luminosity: "luminosity",
        } as const;
        export type BlendMode = (typeof BlendMode)[keyof typeof BlendMode];
        export const ReplyType = {
            Reply: "reply",
            Group: "group",
        } as const;
        export type ReplyType = (typeof ReplyType)[keyof typeof ReplyType];
        export const Intent = {
            FreeText: "free-text",
            FreeTextCallout: "free-text-callout",
        } as const;
        export type Intent = (typeof Intent)[keyof typeof Intent];
        export const FontFamily = {
            Courier: "courier",
            CourierBold: "courier-bold",
            CourierBoldOblique: "courier-bold-oblique",
            CourierOblique: "courier-oblique",
            Helvetica: "helvetica",
            HelveticaBold: "helvetica-bold",
            HelveticaBoldOblique: "helvetica-bold-oblique",
            HelveticaOblique: "helvetica-oblique",
            TimesRoman: "times-roman",
            TimesBold: "times-bold",
            TimesBoldItalic: "times-bold-italic",
            TimesItalic: "times-italic",
            Symbol: "symbol",
            ZapfDingbats: "zapf-dingbats",
        } as const;
        export type FontFamily = (typeof FontFamily)[keyof typeof FontFamily];
        export const TextAlign = {
            Left: "left",
            Center: "center",
            Right: "right",
        } as const;
        export type TextAlign = (typeof TextAlign)[keyof typeof TextAlign];

        export interface Color {
            r: number;
            g: number;
            b: number;
        }

        export interface FontColor {
            r: number;
            g: number;
            b: number;
        }

        export interface InteriorColor {
            r: number;
            g: number;
            b: number;
        }

        export const BorderStyle = {
            Solid: "solid",
            Dashed: "dashed",
            Beveled: "beveled",
            Inset: "inset",
        } as const;
        export type BorderStyle = (typeof BorderStyle)[keyof typeof BorderStyle];

        export interface RectDifferences {
            left: number;
            top: number;
            right: number;
            bottom: number;
        }

        export const LineEnding = {
            None: "none",
            Square: "square",
            Circle: "circle",
            Diamond: "diamond",
            OpenArrow: "open-arrow",
            ClosedArrow: "closed-arrow",
            Butt: "butt",
            ROpenArrow: "r-open-arrow",
            RClosedArrow: "r-closed-arrow",
            Slash: "slash",
        } as const;
        export type LineEnding = (typeof LineEnding)[keyof typeof LineEnding];

        export interface UnrotatedRect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }
    }

    export interface Caret {
        subtype: "caret";
        ref: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretRef;
        pageObjectNumber: number;
        index: number;
        identityQuality: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaret.IdentityQuality;
        nm: string | null;
        flags: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaret.Flags;
        rect: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaret.Rect;
        contents: string | null;
        subject: string | null;
        author: string | null;
        created: string | null;
        modified: string | null;
        blendMode: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaret.BlendMode;
        inReplyTo: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretInReplyTo | null;
        replyType: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaret.ReplyType | null;
        userId?: string | undefined;
        groupId?: string | undefined;
        createdBy?: string | undefined;
        updatedBy?: string | undefined;
        actions?: CloudPDF.PdfAnnotationActions | undefined;
        color: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaret.Color;
        opacity: number;
        intent: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaret.Intent | null;
        rectDifferences: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaret.RectDifferences | null;
        rotation?: number | undefined;
        unrotatedRect?: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaret.UnrotatedRect | undefined;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaret {
        export const IdentityQuality = {
            Durable: "durable",
            Weak: "weak",
        } as const;
        export type IdentityQuality = (typeof IdentityQuality)[keyof typeof IdentityQuality];

        export interface Flags {
            invisible: boolean;
            hidden: boolean;
            print: boolean;
            noZoom: boolean;
            noRotate: boolean;
            noView: boolean;
            readOnly: boolean;
            locked: boolean;
            toggleNoView: boolean;
            lockedContents: boolean;
        }

        export interface Rect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }

        export const BlendMode = {
            Normal: "normal",
            Multiply: "multiply",
            Screen: "screen",
            Overlay: "overlay",
            Darken: "darken",
            Lighten: "lighten",
            ColorDodge: "color-dodge",
            ColorBurn: "color-burn",
            HardLight: "hard-light",
            SoftLight: "soft-light",
            Difference: "difference",
            Exclusion: "exclusion",
            Hue: "hue",
            Saturation: "saturation",
            Color: "color",
            Luminosity: "luminosity",
        } as const;
        export type BlendMode = (typeof BlendMode)[keyof typeof BlendMode];
        export const ReplyType = {
            Reply: "reply",
            Group: "group",
        } as const;
        export type ReplyType = (typeof ReplyType)[keyof typeof ReplyType];

        export interface Color {
            r: number;
            g: number;
            b: number;
        }

        export const Intent = {
            Replace: "replace",
        } as const;
        export type Intent = (typeof Intent)[keyof typeof Intent];

        export interface RectDifferences {
            left: number;
            top: number;
            right: number;
            bottom: number;
        }

        export interface UnrotatedRect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }
    }

    export interface Text {
        subtype: "text";
        ref: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextRef;
        pageObjectNumber: number;
        index: number;
        identityQuality: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemText.IdentityQuality;
        nm: string | null;
        flags: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemText.Flags;
        rect: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemText.Rect;
        contents: string | null;
        subject: string | null;
        author: string | null;
        created: string | null;
        modified: string | null;
        blendMode: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemText.BlendMode;
        inReplyTo: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextInReplyTo | null;
        replyType: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemText.ReplyType | null;
        userId?: string | undefined;
        groupId?: string | undefined;
        createdBy?: string | undefined;
        updatedBy?: string | undefined;
        actions?: CloudPDF.PdfAnnotationActions | undefined;
        color: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemText.Color;
        opacity: number;
        icon: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemText.Icon;
        state: string | null;
        stateModel: string | null;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemText {
        export const IdentityQuality = {
            Durable: "durable",
            Weak: "weak",
        } as const;
        export type IdentityQuality = (typeof IdentityQuality)[keyof typeof IdentityQuality];

        export interface Flags {
            invisible: boolean;
            hidden: boolean;
            print: boolean;
            noZoom: boolean;
            noRotate: boolean;
            noView: boolean;
            readOnly: boolean;
            locked: boolean;
            toggleNoView: boolean;
            lockedContents: boolean;
        }

        export interface Rect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }

        export const BlendMode = {
            Normal: "normal",
            Multiply: "multiply",
            Screen: "screen",
            Overlay: "overlay",
            Darken: "darken",
            Lighten: "lighten",
            ColorDodge: "color-dodge",
            ColorBurn: "color-burn",
            HardLight: "hard-light",
            SoftLight: "soft-light",
            Difference: "difference",
            Exclusion: "exclusion",
            Hue: "hue",
            Saturation: "saturation",
            Color: "color",
            Luminosity: "luminosity",
        } as const;
        export type BlendMode = (typeof BlendMode)[keyof typeof BlendMode];
        export const ReplyType = {
            Reply: "reply",
            Group: "group",
        } as const;
        export type ReplyType = (typeof ReplyType)[keyof typeof ReplyType];

        export interface Color {
            r: number;
            g: number;
            b: number;
        }

        export const Icon = {
            Comment: "comment",
            Key: "key",
            Note: "note",
            Help: "help",
            NewParagraph: "new-paragraph",
            Paragraph: "paragraph",
            Insert: "insert",
        } as const;
        export type Icon = (typeof Icon)[keyof typeof Icon];
    }

    export interface Stamp {
        subtype: "stamp";
        ref: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampRef;
        pageObjectNumber: number;
        index: number;
        identityQuality: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStamp.IdentityQuality;
        nm: string | null;
        flags: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStamp.Flags;
        rect: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStamp.Rect;
        contents: string | null;
        subject: string | null;
        author: string | null;
        created: string | null;
        modified: string | null;
        blendMode: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStamp.BlendMode;
        inReplyTo: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampInReplyTo | null;
        replyType: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStamp.ReplyType | null;
        userId?: string | undefined;
        groupId?: string | undefined;
        createdBy?: string | undefined;
        updatedBy?: string | undefined;
        actions?: CloudPDF.PdfAnnotationActions | undefined;
        name: string | null;
        rotation?: number | undefined;
        unrotatedRect?: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStamp.UnrotatedRect | undefined;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStamp {
        export const IdentityQuality = {
            Durable: "durable",
            Weak: "weak",
        } as const;
        export type IdentityQuality = (typeof IdentityQuality)[keyof typeof IdentityQuality];

        export interface Flags {
            invisible: boolean;
            hidden: boolean;
            print: boolean;
            noZoom: boolean;
            noRotate: boolean;
            noView: boolean;
            readOnly: boolean;
            locked: boolean;
            toggleNoView: boolean;
            lockedContents: boolean;
        }

        export interface Rect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }

        export const BlendMode = {
            Normal: "normal",
            Multiply: "multiply",
            Screen: "screen",
            Overlay: "overlay",
            Darken: "darken",
            Lighten: "lighten",
            ColorDodge: "color-dodge",
            ColorBurn: "color-burn",
            HardLight: "hard-light",
            SoftLight: "soft-light",
            Difference: "difference",
            Exclusion: "exclusion",
            Hue: "hue",
            Saturation: "saturation",
            Color: "color",
            Luminosity: "luminosity",
        } as const;
        export type BlendMode = (typeof BlendMode)[keyof typeof BlendMode];
        export const ReplyType = {
            Reply: "reply",
            Group: "group",
        } as const;
        export type ReplyType = (typeof ReplyType)[keyof typeof ReplyType];

        export interface UnrotatedRect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }
    }

    export interface FileAttachment {
        subtype: "file-attachment";
        ref: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentRef;
        pageObjectNumber: number;
        index: number;
        identityQuality: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachment.IdentityQuality;
        nm: string | null;
        flags: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachment.Flags;
        rect: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachment.Rect;
        contents: string | null;
        subject: string | null;
        author: string | null;
        created: string | null;
        modified: string | null;
        blendMode: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachment.BlendMode;
        inReplyTo: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentInReplyTo | null;
        replyType: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachment.ReplyType | null;
        userId?: string | undefined;
        groupId?: string | undefined;
        createdBy?: string | undefined;
        updatedBy?: string | undefined;
        actions?: CloudPDF.PdfAnnotationActions | undefined;
        color: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachment.Color;
        opacity: number;
        icon: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachment.Icon;
        file: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachment.File_;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachment {
        export const IdentityQuality = {
            Durable: "durable",
            Weak: "weak",
        } as const;
        export type IdentityQuality = (typeof IdentityQuality)[keyof typeof IdentityQuality];

        export interface Flags {
            invisible: boolean;
            hidden: boolean;
            print: boolean;
            noZoom: boolean;
            noRotate: boolean;
            noView: boolean;
            readOnly: boolean;
            locked: boolean;
            toggleNoView: boolean;
            lockedContents: boolean;
        }

        export interface Rect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }

        export const BlendMode = {
            Normal: "normal",
            Multiply: "multiply",
            Screen: "screen",
            Overlay: "overlay",
            Darken: "darken",
            Lighten: "lighten",
            ColorDodge: "color-dodge",
            ColorBurn: "color-burn",
            HardLight: "hard-light",
            SoftLight: "soft-light",
            Difference: "difference",
            Exclusion: "exclusion",
            Hue: "hue",
            Saturation: "saturation",
            Color: "color",
            Luminosity: "luminosity",
        } as const;
        export type BlendMode = (typeof BlendMode)[keyof typeof BlendMode];
        export const ReplyType = {
            Reply: "reply",
            Group: "group",
        } as const;
        export type ReplyType = (typeof ReplyType)[keyof typeof ReplyType];

        export interface Color {
            r: number;
            g: number;
            b: number;
        }

        export const Icon = {
            PushPin: "push-pin",
            Paperclip: "paperclip",
            Graph: "graph",
            Tag: "tag",
        } as const;
        export type Icon = (typeof Icon)[keyof typeof Icon];

        export interface File_ {
            name: string;
            mimeType?: string | undefined;
            description?: string | undefined;
            size?: number | undefined;
            checksum?: string | undefined;
            creationDate?: string | undefined;
        }
    }

    export interface Widget {
        subtype: "widget";
        ref: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetRef;
        pageObjectNumber: number;
        index: number;
        identityQuality: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidget.IdentityQuality;
        nm: string | null;
        flags: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidget.Flags;
        rect: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidget.Rect;
        contents: string | null;
        subject: string | null;
        author: string | null;
        created: string | null;
        modified: string | null;
        blendMode: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidget.BlendMode;
        inReplyTo: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetInReplyTo | null;
        replyType: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidget.ReplyType | null;
        userId?: string | undefined;
        groupId?: string | undefined;
        createdBy?: string | undefined;
        updatedBy?: string | undefined;
        actions?: CloudPDF.PdfAnnotationActions | undefined;
        color: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidget.Color | null;
        interiorColor: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidget.InteriorColor | null;
        strokeWidth: number;
        borderStyle: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidget.BorderStyle;
        fontFamily?: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidget.FontFamily | undefined;
        fontSize?: number | undefined;
        fontColor?: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidget.FontColor | undefined;
        textAlign: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidget.TextAlign;
        fieldObjectNumber: number;
        fieldFamily: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidget.FieldFamily;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidget {
        export const IdentityQuality = {
            Durable: "durable",
            Weak: "weak",
        } as const;
        export type IdentityQuality = (typeof IdentityQuality)[keyof typeof IdentityQuality];

        export interface Flags {
            invisible: boolean;
            hidden: boolean;
            print: boolean;
            noZoom: boolean;
            noRotate: boolean;
            noView: boolean;
            readOnly: boolean;
            locked: boolean;
            toggleNoView: boolean;
            lockedContents: boolean;
        }

        export interface Rect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }

        export const BlendMode = {
            Normal: "normal",
            Multiply: "multiply",
            Screen: "screen",
            Overlay: "overlay",
            Darken: "darken",
            Lighten: "lighten",
            ColorDodge: "color-dodge",
            ColorBurn: "color-burn",
            HardLight: "hard-light",
            SoftLight: "soft-light",
            Difference: "difference",
            Exclusion: "exclusion",
            Hue: "hue",
            Saturation: "saturation",
            Color: "color",
            Luminosity: "luminosity",
        } as const;
        export type BlendMode = (typeof BlendMode)[keyof typeof BlendMode];
        export const ReplyType = {
            Reply: "reply",
            Group: "group",
        } as const;
        export type ReplyType = (typeof ReplyType)[keyof typeof ReplyType];

        export interface Color {
            r: number;
            g: number;
            b: number;
        }

        export interface InteriorColor {
            r: number;
            g: number;
            b: number;
        }

        export const BorderStyle = {
            Solid: "solid",
            Dashed: "dashed",
            Beveled: "beveled",
            Inset: "inset",
        } as const;
        export type BorderStyle = (typeof BorderStyle)[keyof typeof BorderStyle];
        export const FontFamily = {
            Courier: "courier",
            CourierBold: "courier-bold",
            CourierBoldOblique: "courier-bold-oblique",
            CourierOblique: "courier-oblique",
            Helvetica: "helvetica",
            HelveticaBold: "helvetica-bold",
            HelveticaBoldOblique: "helvetica-bold-oblique",
            HelveticaOblique: "helvetica-oblique",
            TimesRoman: "times-roman",
            TimesBold: "times-bold",
            TimesBoldItalic: "times-bold-italic",
            TimesItalic: "times-italic",
            Symbol: "symbol",
            ZapfDingbats: "zapf-dingbats",
        } as const;
        export type FontFamily = (typeof FontFamily)[keyof typeof FontFamily];

        export interface FontColor {
            r: number;
            g: number;
            b: number;
        }

        export const TextAlign = {
            Left: "left",
            Center: "center",
            Right: "right",
        } as const;
        export type TextAlign = (typeof TextAlign)[keyof typeof TextAlign];
        export const FieldFamily = {
            Text: "text",
            Checkbox: "checkbox",
            Radio: "radio",
            Combobox: "combobox",
            Listbox: "listbox",
            Pushbutton: "pushbutton",
            Signature: "signature",
            Unknown: "unknown",
        } as const;
        export type FieldFamily = (typeof FieldFamily)[keyof typeof FieldFamily];
    }

    export interface Redact {
        subtype: "redact";
        ref: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactRef;
        pageObjectNumber: number;
        index: number;
        identityQuality: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedact.IdentityQuality;
        nm: string | null;
        flags: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedact.Flags;
        rect: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedact.Rect;
        contents: string | null;
        subject: string | null;
        author: string | null;
        created: string | null;
        modified: string | null;
        blendMode: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedact.BlendMode;
        inReplyTo: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactInReplyTo | null;
        replyType: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedact.ReplyType | null;
        userId?: string | undefined;
        groupId?: string | undefined;
        createdBy?: string | undefined;
        updatedBy?: string | undefined;
        actions?: CloudPDF.PdfAnnotationActions | undefined;
        quadPoints: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedact.QuadPoints.Item[];
        color: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedact.Color;
        opacity: number;
        interiorColor: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedact.InteriorColor | null;
        overlayText: string | null;
        repeat: boolean;
        fontFamily: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedact.FontFamily;
        fontSize: number;
        fontColor: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedact.FontColor;
        textAlign: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedact.TextAlign;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedact {
        export const IdentityQuality = {
            Durable: "durable",
            Weak: "weak",
        } as const;
        export type IdentityQuality = (typeof IdentityQuality)[keyof typeof IdentityQuality];

        export interface Flags {
            invisible: boolean;
            hidden: boolean;
            print: boolean;
            noZoom: boolean;
            noRotate: boolean;
            noView: boolean;
            readOnly: boolean;
            locked: boolean;
            toggleNoView: boolean;
            lockedContents: boolean;
        }

        export interface Rect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }

        export const BlendMode = {
            Normal: "normal",
            Multiply: "multiply",
            Screen: "screen",
            Overlay: "overlay",
            Darken: "darken",
            Lighten: "lighten",
            ColorDodge: "color-dodge",
            ColorBurn: "color-burn",
            HardLight: "hard-light",
            SoftLight: "soft-light",
            Difference: "difference",
            Exclusion: "exclusion",
            Hue: "hue",
            Saturation: "saturation",
            Color: "color",
            Luminosity: "luminosity",
        } as const;
        export type BlendMode = (typeof BlendMode)[keyof typeof BlendMode];
        export const ReplyType = {
            Reply: "reply",
            Group: "group",
        } as const;
        export type ReplyType = (typeof ReplyType)[keyof typeof ReplyType];
        export type QuadPoints = QuadPoints.Item[];

        export namespace QuadPoints {
            export interface Item {
                p1: Item.P1;
                p2: Item.P2;
                p3: Item.P3;
                p4: Item.P4;
            }

            export namespace Item {
                export interface P1 {
                    x: number;
                    y: number;
                }

                export interface P2 {
                    x: number;
                    y: number;
                }

                export interface P3 {
                    x: number;
                    y: number;
                }

                export interface P4 {
                    x: number;
                    y: number;
                }
            }
        }

        export interface Color {
            r: number;
            g: number;
            b: number;
        }

        export interface InteriorColor {
            r: number;
            g: number;
            b: number;
        }

        export const FontFamily = {
            Courier: "courier",
            CourierBold: "courier-bold",
            CourierBoldOblique: "courier-bold-oblique",
            CourierOblique: "courier-oblique",
            Helvetica: "helvetica",
            HelveticaBold: "helvetica-bold",
            HelveticaBoldOblique: "helvetica-bold-oblique",
            HelveticaOblique: "helvetica-oblique",
            TimesRoman: "times-roman",
            TimesBold: "times-bold",
            TimesBoldItalic: "times-bold-italic",
            TimesItalic: "times-italic",
            Symbol: "symbol",
            ZapfDingbats: "zapf-dingbats",
        } as const;
        export type FontFamily = (typeof FontFamily)[keyof typeof FontFamily];

        export interface FontColor {
            r: number;
            g: number;
            b: number;
        }

        export const TextAlign = {
            Left: "left",
            Center: "center",
            Right: "right",
        } as const;
        export type TextAlign = (typeof TextAlign)[keyof typeof TextAlign];
    }

    export interface Unsupported {
        subtype: "unsupported";
        ref: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedRef;
        pageObjectNumber: number;
        index: number;
        identityQuality: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupported.IdentityQuality;
        nm: string | null;
        flags: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupported.Flags;
        rect: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupported.Rect;
        contents: string | null;
        subject: string | null;
        author: string | null;
        created: string | null;
        modified: string | null;
        blendMode: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupported.BlendMode;
        inReplyTo: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedInReplyTo | null;
        replyType: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupported.ReplyType | null;
        userId?: string | undefined;
        groupId?: string | undefined;
        createdBy?: string | undefined;
        updatedBy?: string | undefined;
        actions?: CloudPDF.PdfAnnotationActions | undefined;
        rawSubtypeCode: number;
        rawSubtypeName: string | null;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupported {
        export const IdentityQuality = {
            Durable: "durable",
            Weak: "weak",
        } as const;
        export type IdentityQuality = (typeof IdentityQuality)[keyof typeof IdentityQuality];

        export interface Flags {
            invisible: boolean;
            hidden: boolean;
            print: boolean;
            noZoom: boolean;
            noRotate: boolean;
            noView: boolean;
            readOnly: boolean;
            locked: boolean;
            toggleNoView: boolean;
            lockedContents: boolean;
        }

        export interface Rect {
            left: number;
            bottom: number;
            right: number;
            top: number;
        }

        export const BlendMode = {
            Normal: "normal",
            Multiply: "multiply",
            Screen: "screen",
            Overlay: "overlay",
            Darken: "darken",
            Lighten: "lighten",
            ColorDodge: "color-dodge",
            ColorBurn: "color-burn",
            HardLight: "hard-light",
            SoftLight: "soft-light",
            Difference: "difference",
            Exclusion: "exclusion",
            Hue: "hue",
            Saturation: "saturation",
            Color: "color",
            Luminosity: "luminosity",
        } as const;
        export type BlendMode = (typeof BlendMode)[keyof typeof BlendMode];
        export const ReplyType = {
            Reply: "reply",
            Group: "group",
        } as const;
        export type ReplyType = (typeof ReplyType)[keyof typeof ReplyType];
    }
}
