// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponsePageStateWeakAnnotationState =
    | CloudPDF.DocAnnotationsList200ResponsePageStateWeakAnnotationState.Unknown
    | CloudPDF.DocAnnotationsList200ResponsePageStateWeakAnnotationState.Known;

export namespace DocAnnotationsList200ResponsePageStateWeakAnnotationState {
    export interface Unknown {
        kind: "unknown";
    }

    export interface Known {
        kind: "known";
        hasAnyWeakAnnotations: boolean;
    }
}
