// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemPolylineRef =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineRef.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineRef.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineRef.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemPolylineRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemPolylineRefIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemPolylineRefIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
