// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemLineInReplyTo =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineInReplyTo.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineInReplyTo.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineInReplyTo.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemLineInReplyTo {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemLineInReplyToIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemLineInReplyToIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
