// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyInReplyTo =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyInReplyTo.ObjectNumber
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyInReplyTo.Nm
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyInReplyTo.Index;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyInReplyTo {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyInReplyToIndex.Revision;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyInReplyToIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
