// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export interface DocAnnotationsList200Response {
    pageState: DocAnnotationsList200Response.PageState;
    annotations: CloudPDF.DocAnnotationsList200ResponseAnnotationsItem[];
}

export namespace DocAnnotationsList200Response {
    export interface PageState {
        pageObjectNumber: number;
        revision: PageState.Revision;
        weakAnnotationState: CloudPDF.DocAnnotationsList200ResponsePageStateWeakAnnotationState;
    }

    export namespace PageState {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
