// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentRef =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentRef.ObjectNumber
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentRef.Nm
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentRef.Index;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentRefIndex.Revision;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentRefIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
