// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemWidgetRef =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetRef.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetRef.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetRef.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemWidgetRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemWidgetRefIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemWidgetRefIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
