// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemUnsupportedInReplyTo =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedInReplyTo.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedInReplyTo.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedInReplyTo.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemUnsupportedInReplyTo {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemUnsupportedInReplyToIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemUnsupportedInReplyToIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
