// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemFileAttachmentRef =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemFileAttachmentRef.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemFileAttachmentRef.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemFileAttachmentRef.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemFileAttachmentRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemFileAttachmentRefIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemFileAttachmentRefIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
