// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemSquareRef =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareRef.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareRef.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareRef.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemSquareRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemSquareRefIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemSquareRefIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
