// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemPolygonRef =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonRef.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonRef.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonRef.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemPolygonRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemPolygonRefIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemPolygonRefIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
