// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkInReplyTo =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkInReplyTo.ObjectNumber
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkInReplyTo.Nm
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkInReplyTo.Index;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkInReplyTo {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkInReplyToIndex.Revision;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkInReplyToIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
