// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemLinkTargetGotoDestination =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkTargetGotoDestination.Xyz
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkTargetGotoDestination.Fit
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkTargetGotoDestination.FitH
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkTargetGotoDestination.FitV
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkTargetGotoDestination.FitR
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkTargetGotoDestination.FitB
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkTargetGotoDestination.FitBh
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkTargetGotoDestination.FitBv;

export namespace DocAnnotationsList200ResponseAnnotationsItemLinkTargetGotoDestination {
    export interface Xyz {
        kind: "xyz";
        pageObjectNumber: number;
        left?: (number | null) | undefined;
        top?: (number | null) | undefined;
        zoom?: (number | null) | undefined;
    }

    export interface Fit {
        kind: "fit";
        pageObjectNumber: number;
    }

    export interface FitH {
        kind: "fitH";
        pageObjectNumber: number;
        top?: (number | null) | undefined;
    }

    export interface FitV {
        kind: "fitV";
        pageObjectNumber: number;
        left?: (number | null) | undefined;
    }

    export interface FitR {
        kind: "fitR";
        pageObjectNumber: number;
        left: number;
        bottom: number;
        right: number;
        top: number;
    }

    export interface FitB {
        kind: "fitB";
        pageObjectNumber: number;
    }

    export interface FitBh {
        kind: "fitBH";
        pageObjectNumber: number;
        top?: (number | null) | undefined;
    }

    export interface FitBv {
        kind: "fitBV";
        pageObjectNumber: number;
        left?: (number | null) | undefined;
    }
}
