// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemRedactRef =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemRedactRef.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemRedactRef.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemRedactRef.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemRedactRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        pageObjectNumber: number;
        annotObjectNumber: number;
    }

    export interface Nm {
        kind: "nm";
        pageObjectNumber: number;
        nm: string;
    }

    export interface Index {
        kind: "index";
        pageObjectNumber: number;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemRedactRefIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemRedactRefIndex {
        export interface Revision {
            docSessionId: string;
            pageObjectNumber: number;
            generation: number;
        }
    }
}
