// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemCheckboxValueEntry =
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxValueEntry.None
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxValueEntry.Scalar
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxValueEntry.Array
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxValueEntry.Unsupported;

export namespace DocFormsGet200ResponseFieldsItemCheckboxValueEntry {
    export interface None {
        kind: "none";
    }

    export interface Scalar {
        kind: "scalar";
        value: string;
    }

    export interface Array {
        kind: "array";
        values: string[];
    }

    export interface Unsupported {
        kind: "unsupported";
    }
}
