// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemComboboxValueEntry =
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxValueEntry.None
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxValueEntry.Scalar
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxValueEntry.Array
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxValueEntry.Unsupported;

export namespace DocFormsGet200ResponseFieldsItemComboboxValueEntry {
    export interface None {
        kind: "none";
    }

    export interface Scalar {
        kind: "scalar";
        value: string;
    }

    export interface Array {
        kind: "array";
        values: string[];
    }

    export interface Unsupported {
        kind: "unsupported";
    }
}
