// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemSignatureRef =
    | CloudPDF.DocFormsGet200ResponseFieldsItemSignatureRef.ObjectNumber
    | CloudPDF.DocFormsGet200ResponseFieldsItemSignatureRef.Fqn;

export namespace DocFormsGet200ResponseFieldsItemSignatureRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        fieldObjectNumber: number;
    }

    export interface Fqn {
        kind: "fqn";
        name: string;
    }
}
