// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItem =
    | CloudPDF.DocFormsGet200ResponseFieldsItem.Text
    | CloudPDF.DocFormsGet200ResponseFieldsItem.Checkbox
    | CloudPDF.DocFormsGet200ResponseFieldsItem.Radio
    | CloudPDF.DocFormsGet200ResponseFieldsItem.Combobox
    | CloudPDF.DocFormsGet200ResponseFieldsItem.Listbox
    | CloudPDF.DocFormsGet200ResponseFieldsItem.Pushbutton
    | CloudPDF.DocFormsGet200ResponseFieldsItem.Signature
    | CloudPDF.DocFormsGet200ResponseFieldsItem.Unknown;

export namespace DocFormsGet200ResponseFieldsItem {
    export interface Text {
        family: "text";
        ref: CloudPDF.DocFormsGet200ResponseFieldsItemTextRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsGet200ResponseFieldsItemText.Origin;
        flags: DocFormsGet200ResponseFieldsItemText.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsGet200ResponseFieldsItemTextValueEntry;
        defaultValueEntry: CloudPDF.DocFormsGet200ResponseFieldsItemTextDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsGet200ResponseFieldsItemText.Widgets.Item[];
        value: string;
        defaultValue: string;
        maxLength: number | null;
        multiline: boolean;
        password: boolean;
        comb: boolean;
    }

    export namespace DocFormsGet200ResponseFieldsItemText {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                annotObjectNumber: number;
                pageObjectNumber: number;
            }
        }
    }

    export interface Checkbox {
        family: "checkbox";
        ref: CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsGet200ResponseFieldsItemCheckbox.Origin;
        flags: DocFormsGet200ResponseFieldsItemCheckbox.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxValueEntry;
        defaultValueEntry: CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsGet200ResponseFieldsItemCheckbox.Widgets.Item[];
        checked: boolean;
        exportValue: string;
    }

    export namespace DocFormsGet200ResponseFieldsItemCheckbox {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                annotObjectNumber: number;
                pageObjectNumber: number;
                onState: string;
                exportValue: string;
                checked: boolean;
            }
        }
    }

    export interface Radio {
        family: "radio";
        ref: CloudPDF.DocFormsGet200ResponseFieldsItemRadioRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsGet200ResponseFieldsItemRadio.Origin;
        flags: DocFormsGet200ResponseFieldsItemRadio.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsGet200ResponseFieldsItemRadioValueEntry;
        defaultValueEntry: CloudPDF.DocFormsGet200ResponseFieldsItemRadioDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsGet200ResponseFieldsItemRadio.Widgets.Item[];
        value: string;
        radiosInUnison: boolean;
        noToggleToOff: boolean;
    }

    export namespace DocFormsGet200ResponseFieldsItemRadio {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                annotObjectNumber: number;
                pageObjectNumber: number;
                onState: string;
                exportValue: string;
                checked: boolean;
            }
        }
    }

    export interface Combobox {
        family: "combobox";
        ref: CloudPDF.DocFormsGet200ResponseFieldsItemComboboxRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsGet200ResponseFieldsItemCombobox.Origin;
        flags: DocFormsGet200ResponseFieldsItemCombobox.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsGet200ResponseFieldsItemComboboxValueEntry;
        defaultValueEntry: CloudPDF.DocFormsGet200ResponseFieldsItemComboboxDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsGet200ResponseFieldsItemCombobox.Widgets.Item[];
        value: string;
        defaultValue: string;
        edit: boolean;
        options: DocFormsGet200ResponseFieldsItemCombobox.Options.Item[];
    }

    export namespace DocFormsGet200ResponseFieldsItemCombobox {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                annotObjectNumber: number;
                pageObjectNumber: number;
            }
        }

        export type Options = Options.Item[];

        export namespace Options {
            export interface Item {
                label: string;
                value: string;
                selected: boolean;
            }
        }
    }

    export interface Listbox {
        family: "listbox";
        ref: CloudPDF.DocFormsGet200ResponseFieldsItemListboxRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsGet200ResponseFieldsItemListbox.Origin;
        flags: DocFormsGet200ResponseFieldsItemListbox.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsGet200ResponseFieldsItemListboxValueEntry;
        defaultValueEntry: CloudPDF.DocFormsGet200ResponseFieldsItemListboxDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsGet200ResponseFieldsItemListbox.Widgets.Item[];
        selectedValues: string[];
        multiSelect: boolean;
        options: DocFormsGet200ResponseFieldsItemListbox.Options.Item[];
    }

    export namespace DocFormsGet200ResponseFieldsItemListbox {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                annotObjectNumber: number;
                pageObjectNumber: number;
            }
        }

        export type Options = Options.Item[];

        export namespace Options {
            export interface Item {
                label: string;
                value: string;
                selected: boolean;
            }
        }
    }

    export interface Pushbutton {
        family: "pushbutton";
        ref: CloudPDF.DocFormsGet200ResponseFieldsItemPushbuttonRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsGet200ResponseFieldsItemPushbutton.Origin;
        flags: DocFormsGet200ResponseFieldsItemPushbutton.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsGet200ResponseFieldsItemPushbuttonValueEntry;
        defaultValueEntry: CloudPDF.DocFormsGet200ResponseFieldsItemPushbuttonDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsGet200ResponseFieldsItemPushbutton.Widgets.Item[];
    }

    export namespace DocFormsGet200ResponseFieldsItemPushbutton {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                annotObjectNumber: number;
                pageObjectNumber: number;
            }
        }
    }

    export interface Signature {
        family: "signature";
        ref: CloudPDF.DocFormsGet200ResponseFieldsItemSignatureRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsGet200ResponseFieldsItemSignature.Origin;
        flags: DocFormsGet200ResponseFieldsItemSignature.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsGet200ResponseFieldsItemSignatureValueEntry;
        defaultValueEntry: CloudPDF.DocFormsGet200ResponseFieldsItemSignatureDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsGet200ResponseFieldsItemSignature.Widgets.Item[];
    }

    export namespace DocFormsGet200ResponseFieldsItemSignature {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                annotObjectNumber: number;
                pageObjectNumber: number;
            }
        }
    }

    export interface Unknown {
        family: "unknown";
        ref: CloudPDF.DocFormsGet200ResponseFieldsItemUnknownRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsGet200ResponseFieldsItemUnknown.Origin;
        flags: DocFormsGet200ResponseFieldsItemUnknown.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsGet200ResponseFieldsItemUnknownValueEntry;
        defaultValueEntry: CloudPDF.DocFormsGet200ResponseFieldsItemUnknownDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsGet200ResponseFieldsItemUnknown.Widgets.Item[];
        rawValue: string;
    }

    export namespace DocFormsGet200ResponseFieldsItemUnknown {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                annotObjectNumber: number;
                pageObjectNumber: number;
            }
        }
    }
}
