// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemTextDefaultValueEntry =
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextDefaultValueEntry.None
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextDefaultValueEntry.Scalar
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextDefaultValueEntry.Array
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextDefaultValueEntry.Unsupported;

export namespace DocFormsGet200ResponseFieldsItemTextDefaultValueEntry {
    export interface None {
        kind: "none";
    }

    export interface Scalar {
        kind: "scalar";
        value: string;
    }

    export interface Array {
        kind: "array";
        values: string[];
    }

    export interface Unsupported {
        kind: "unsupported";
    }
}
