// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export interface DocFormsGet200Response {
    formKind: DocFormsGet200Response.FormKind;
    needsAppearances: boolean;
    fields: CloudPDF.DocFormsGet200ResponseFieldsItem[];
    calculationOrder: (CloudPDF.DocFormsGet200ResponseCalculationOrderItem | null)[];
}

export namespace DocFormsGet200Response {
    export const FormKind = {
        None: "none",
        Acroform: "acroform",
        Xfa: "xfa",
    } as const;
    export type FormKind = (typeof FormKind)[keyof typeof FormKind];
}
