// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseCalculationOrderItem =
    | CloudPDF.DocFormsGet200ResponseCalculationOrderItem.ObjectNumber
    | CloudPDF.DocFormsGet200ResponseCalculationOrderItem.Fqn;

export namespace DocFormsGet200ResponseCalculationOrderItem {
    export interface ObjectNumber {
        kind: "objectNumber";
        fieldObjectNumber: number;
    }

    export interface Fqn {
        kind: "fqn";
        name: string;
    }
}
