// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemComboboxDefaultValueEntry =
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxDefaultValueEntry.None
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxDefaultValueEntry.Scalar
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxDefaultValueEntry.Array
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxDefaultValueEntry.Unsupported;

export namespace DocFormsGet200ResponseFieldsItemComboboxDefaultValueEntry {
    export interface None {
        kind: "none";
    }

    export interface Scalar {
        kind: "scalar";
        value: string;
    }

    export interface Array {
        kind: "array";
        values: string[];
    }

    export interface Unsupported {
        kind: "unsupported";
    }
}
