// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemUnknownDefaultValueEntry =
    | CloudPDF.DocFormsGet200ResponseFieldsItemUnknownDefaultValueEntry.None
    | CloudPDF.DocFormsGet200ResponseFieldsItemUnknownDefaultValueEntry.Scalar
    | CloudPDF.DocFormsGet200ResponseFieldsItemUnknownDefaultValueEntry.Array
    | CloudPDF.DocFormsGet200ResponseFieldsItemUnknownDefaultValueEntry.Unsupported;

export namespace DocFormsGet200ResponseFieldsItemUnknownDefaultValueEntry {
    export interface None {
        kind: "none";
    }

    export interface Scalar {
        kind: "scalar";
        value: string;
    }

    export interface Array {
        kind: "array";
        values: string[];
    }

    export interface Unsupported {
        kind: "unsupported";
    }
}
