// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemPushbuttonDefaultValueEntry =
    | CloudPDF.DocFormsGet200ResponseFieldsItemPushbuttonDefaultValueEntry.None
    | CloudPDF.DocFormsGet200ResponseFieldsItemPushbuttonDefaultValueEntry.Scalar
    | CloudPDF.DocFormsGet200ResponseFieldsItemPushbuttonDefaultValueEntry.Array
    | CloudPDF.DocFormsGet200ResponseFieldsItemPushbuttonDefaultValueEntry.Unsupported;

export namespace DocFormsGet200ResponseFieldsItemPushbuttonDefaultValueEntry {
    export interface None {
        kind: "none";
    }

    export interface Scalar {
        kind: "scalar";
        value: string;
    }

    export interface Array {
        kind: "array";
        values: string[];
    }

    export interface Unsupported {
        kind: "unsupported";
    }
}
