// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemUnknownValueEntry =
    | CloudPDF.DocFormsGet200ResponseFieldsItemUnknownValueEntry.None
    | CloudPDF.DocFormsGet200ResponseFieldsItemUnknownValueEntry.Scalar
    | CloudPDF.DocFormsGet200ResponseFieldsItemUnknownValueEntry.Array
    | CloudPDF.DocFormsGet200ResponseFieldsItemUnknownValueEntry.Unsupported;

export namespace DocFormsGet200ResponseFieldsItemUnknownValueEntry {
    export interface None {
        kind: "none";
    }

    export interface Scalar {
        kind: "scalar";
        value: string;
    }

    export interface Array {
        kind: "array";
        values: string[];
    }

    export interface Unsupported {
        kind: "unsupported";
    }
}
