// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemPushbuttonValueEntry =
    | CloudPDF.DocFormsGet200ResponseFieldsItemPushbuttonValueEntry.None
    | CloudPDF.DocFormsGet200ResponseFieldsItemPushbuttonValueEntry.Scalar
    | CloudPDF.DocFormsGet200ResponseFieldsItemPushbuttonValueEntry.Array
    | CloudPDF.DocFormsGet200ResponseFieldsItemPushbuttonValueEntry.Unsupported;

export namespace DocFormsGet200ResponseFieldsItemPushbuttonValueEntry {
    export interface None {
        kind: "none";
    }

    export interface Scalar {
        kind: "scalar";
        value: string;
    }

    export interface Array {
        kind: "array";
        values: string[];
    }

    export interface Unsupported {
        kind: "unsupported";
    }
}
