// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemSignatureValueEntry =
    | CloudPDF.DocFormsGet200ResponseFieldsItemSignatureValueEntry.None
    | CloudPDF.DocFormsGet200ResponseFieldsItemSignatureValueEntry.Scalar
    | CloudPDF.DocFormsGet200ResponseFieldsItemSignatureValueEntry.Array
    | CloudPDF.DocFormsGet200ResponseFieldsItemSignatureValueEntry.Unsupported;

export namespace DocFormsGet200ResponseFieldsItemSignatureValueEntry {
    export interface None {
        kind: "none";
    }

    export interface Scalar {
        kind: "scalar";
        value: string;
    }

    export interface Array {
        kind: "array";
        values: string[];
    }

    export interface Unsupported {
        kind: "unsupported";
    }
}
