// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemRadioValueEntry =
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioValueEntry.None
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioValueEntry.Scalar
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioValueEntry.Array
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioValueEntry.Unsupported;

export namespace DocFormsGet200ResponseFieldsItemRadioValueEntry {
    export interface None {
        kind: "none";
    }

    export interface Scalar {
        kind: "scalar";
        value: string;
    }

    export interface Array {
        kind: "array";
        values: string[];
    }

    export interface Unsupported {
        kind: "unsupported";
    }
}
