// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemCheckboxRef =
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxRef.ObjectNumber
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxRef.Fqn;

export namespace DocFormsGet200ResponseFieldsItemCheckboxRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        fieldObjectNumber: number;
    }

    export interface Fqn {
        kind: "fqn";
        name: string;
    }
}
