// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemRadioDefaultValueEntry =
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioDefaultValueEntry.None
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioDefaultValueEntry.Scalar
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioDefaultValueEntry.Array
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioDefaultValueEntry.Unsupported;

export namespace DocFormsGet200ResponseFieldsItemRadioDefaultValueEntry {
    export interface None {
        kind: "none";
    }

    export interface Scalar {
        kind: "scalar";
        value: string;
    }

    export interface Array {
        kind: "array";
        values: string[];
    }

    export interface Unsupported {
        kind: "unsupported";
    }
}
