// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemSignatureDefaultValueEntry =
    | CloudPDF.DocFormsGet200ResponseFieldsItemSignatureDefaultValueEntry.None
    | CloudPDF.DocFormsGet200ResponseFieldsItemSignatureDefaultValueEntry.Scalar
    | CloudPDF.DocFormsGet200ResponseFieldsItemSignatureDefaultValueEntry.Array
    | CloudPDF.DocFormsGet200ResponseFieldsItemSignatureDefaultValueEntry.Unsupported;

export namespace DocFormsGet200ResponseFieldsItemSignatureDefaultValueEntry {
    export interface None {
        kind: "none";
    }

    export interface Scalar {
        kind: "scalar";
        value: string;
    }

    export interface Array {
        kind: "array";
        values: string[];
    }

    export interface Unsupported {
        kind: "unsupported";
    }
}
