// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export interface DocManifest200Response {
    docVersion: number;
    layoutVersion: number;
    metadataVersion: number;
    actionsVersion?: number | undefined;
    attachmentsVersion?: number | undefined;
    annotationsVersion?: number | undefined;
    auditHead: number;
    baseSha: string;
    scopes?: DocManifest200Response.Scopes | undefined;
    pages: DocManifest200Response.Pages.Item[];
}

export namespace DocManifest200Response {
    export interface Scopes {
        content: Scopes.Content;
        annotations: Scopes.Annotations;
        layout: Scopes.Layout;
        attachments: Scopes.Attachments;
        metadata: Scopes.Metadata;
        actions: Scopes.Actions;
    }

    export namespace Scopes {
        export const Content = {
            Base: "base",
            Layer: "layer",
        } as const;
        export type Content = (typeof Content)[keyof typeof Content];
        export const Annotations = {
            Base: "base",
            Layer: "layer",
        } as const;
        export type Annotations = (typeof Annotations)[keyof typeof Annotations];
        export const Layout = {
            Base: "base",
            Layer: "layer",
        } as const;
        export type Layout = (typeof Layout)[keyof typeof Layout];
        export const Attachments = {
            Base: "base",
            Layer: "layer",
        } as const;
        export type Attachments = (typeof Attachments)[keyof typeof Attachments];
        export const Metadata = {
            Base: "base",
            Layer: "layer",
        } as const;
        export type Metadata = (typeof Metadata)[keyof typeof Metadata];
        export const Actions = {
            Base: "base",
            Layer: "layer",
        } as const;
        export type Actions = (typeof Actions)[keyof typeof Actions];
    }

    export type Pages = Pages.Item[];

    export namespace Pages {
        export interface Item {
            state: Item.State;
            cache: Item.Cache;
        }

        export namespace Item {
            export interface State {
                pageObjectNumber: number;
                revision: State.Revision;
                weakAnnotationState: CloudPDF.DocManifest200ResponsePagesItemStateWeakAnnotationState;
            }

            export namespace State {
                export interface Revision {
                    docSessionId: string;
                    pageObjectNumber: number;
                    generation: number;
                }
            }

            export interface Cache {
                contentVersion: number;
                annotationVersion: number;
            }
        }
    }
}
