// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocManifest200ResponsePagesItemStateWeakAnnotationState =
    | CloudPDF.DocManifest200ResponsePagesItemStateWeakAnnotationState.Unknown
    | CloudPDF.DocManifest200ResponsePagesItemStateWeakAnnotationState.Known;

export namespace DocManifest200ResponsePagesItemStateWeakAnnotationState {
    export interface Unknown {
        kind: "unknown";
    }

    export interface Known {
        kind: "known";
        hasAnyWeakAnnotations: boolean;
    }
}
