// This file was auto-generated by Fern from our API Definition.

export interface DocMetadataGet200Response {
    title: string | null;
    author: string | null;
    subject: string | null;
    keywords: string | null;
    producer: string | null;
    creator: string | null;
    created: string | null;
    modified: string | null;
    trapped: DocMetadataGet200Response.Trapped;
    custom: Record<string, string>;
}

export namespace DocMetadataGet200Response {
    export const Trapped = {
        True: "true",
        False: "false",
        Unknown: "unknown",
    } as const;
    export type Trapped = (typeof Trapped)[keyof typeof Trapped];
}
