// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocPagesFlatten200ResponseMetaAffectedPagesItemWeakAnnotationState =
    | CloudPDF.DocPagesFlatten200ResponseMetaAffectedPagesItemWeakAnnotationState.Unknown
    | CloudPDF.DocPagesFlatten200ResponseMetaAffectedPagesItemWeakAnnotationState.Known;

export namespace DocPagesFlatten200ResponseMetaAffectedPagesItemWeakAnnotationState {
    export interface Unknown {
        kind: "unknown";
    }

    export interface Known {
        kind: "known";
        hasAnyWeakAnnotations: boolean;
    }
}
