// This file was auto-generated by Fern from our API Definition.

export interface DocSignaturesPrepare200Response {
    signingId: string;
    digest: string;
    algorithm: DocSignaturesPrepare200Response.Algorithm;
    byteRange: unknown[];
    contentsSize: number;
    subFilter: string;
    expectedVersion: DocSignaturesPrepare200Response.ExpectedVersion;
    expiresAt: string | null;
}

export namespace DocSignaturesPrepare200Response {
    export const Algorithm = {
        Sha256: "sha256",
        Sha384: "sha384",
        Sha512: "sha512",
    } as const;
    export type Algorithm = (typeof Algorithm)[keyof typeof Algorithm];

    export interface ExpectedVersion {
        baseSha256: string;
        editsVersion: number;
    }
}
