// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocSignaturesList200ResponseSignaturesItemField =
    | CloudPDF.DocSignaturesList200ResponseSignaturesItemField.ObjectNumber
    | CloudPDF.DocSignaturesList200ResponseSignaturesItemField.Fqn;

export namespace DocSignaturesList200ResponseSignaturesItemField {
    export interface ObjectNumber {
        kind: "objectNumber";
        fieldObjectNumber: number;
    }

    export interface Fqn {
        kind: "fqn";
        name: string;
    }
}
