// This file was auto-generated by Fern from our API Definition.

export interface DocSignaturesAbort200Response {
    status: DocSignaturesAbort200Response.Status;
}

export namespace DocSignaturesAbort200Response {
    export const Status = {
        Aborted: "aborted",
        AlreadyCompleted: "already-completed",
        Unknown: "unknown",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
