// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export interface DocSignaturesComplete200Response {
    status: DocSignaturesComplete200Response.Status;
    signature: DocSignaturesComplete200Response.Signature;
    version: DocSignaturesComplete200Response.Version;
    previous: DocSignaturesComplete200Response.Previous;
    protection: DocSignaturesComplete200Response.Protection;
    meta: DocSignaturesComplete200Response.Meta;
}

export namespace DocSignaturesComplete200Response {
    export const Status = {
        Completed: "completed",
        AlreadyCompleted: "already-completed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];

    export interface Signature {
        index: number;
        field: CloudPDF.DocSignaturesComplete200ResponseSignatureField;
        fieldName: string;
        widget: Signature.Widget | null;
        signed: boolean;
        kind: Signature.Kind;
        filter: string | null;
        subFilter: string | null;
        byteRange: unknown[] | null;
        contentsSize: number;
        coverage: Signature.Coverage | null;
        revisionIndex: number | null;
        signer: Signature.Signer;
        docMdp: number | null;
        catalogCertification: boolean;
        fieldMdp: Signature.FieldMdp | null;
        lock: Signature.Lock | null;
        seedValue: Signature.SeedValue | null;
    }

    export namespace Signature {
        export interface Widget {
            annotObjectNumber: number;
            pageObjectNumber: number;
        }

        export const Kind = {
            Signature: "signature",
            Timestamp: "timestamp",
        } as const;
        export type Kind = (typeof Kind)[keyof typeof Kind];
        export const Coverage = {
            WholeRevision: "whole-revision",
            Partial: "partial",
            Malformed: "malformed",
        } as const;
        export type Coverage = (typeof Coverage)[keyof typeof Coverage];

        export interface Signer {
            name: string | null;
            reason: string | null;
            location: string | null;
            contactInfo: string | null;
            claimedTime: string | null;
        }

        export interface FieldMdp {
            action: FieldMdp.Action;
            fields: string[];
            permission?: (number | null) | undefined;
        }

        export namespace FieldMdp {
            export const Action = {
                All: "all",
                Include: "include",
                Exclude: "exclude",
            } as const;
            export type Action = (typeof Action)[keyof typeof Action];
        }

        export interface Lock {
            action: Lock.Action;
            fields: string[];
            permission?: (number | null) | undefined;
        }

        export namespace Lock {
            export const Action = {
                All: "all",
                Include: "include",
                Exclude: "exclude",
            } as const;
            export type Action = (typeof Action)[keyof typeof Action];
        }

        export interface SeedValue {
            requiredFlags: number;
            presentFlags: number;
            version: number | null;
            mdp: number | null;
            filter: string | null;
            subFilters: string[];
            digestMethods: string[];
            reasons: string[];
            unsupportedRequired: boolean;
        }
    }

    export interface Version {
        sha256: string;
        byteLength: number;
    }

    export interface Previous {
        baseSha256: string;
        editsVersion: number;
    }

    export interface Protection {
        enforced: Protection.Enforced | null;
        judged: Protection.Judged | null;
        certification: Protection.Certification | null;
        fieldLocks: Protection.FieldLocks.Item[];
        policyVersion: number;
    }

    export namespace Protection {
        export const Enforced = {
            None: "none",
            Lta: "lta",
            Fill: "fill",
            Annotate: "annotate",
        } as const;
        export type Enforced = (typeof Enforced)[keyof typeof Enforced];
        export const Judged = {
            None: "none",
            Lta: "lta",
            Fill: "fill",
            Annotate: "annotate",
        } as const;
        export type Judged = (typeof Judged)[keyof typeof Judged];

        export interface Certification {
            signatureIndex: number;
            permission: number | null;
        }

        export type FieldLocks = FieldLocks.Item[];

        export namespace FieldLocks {
            export interface Item {
                signatureIndex: number;
                source: Item.Source;
                spec: Item.Spec | null;
            }

            export namespace Item {
                export const Source = {
                    Fieldmdp: "fieldmdp",
                    Lock: "lock",
                } as const;
                export type Source = (typeof Source)[keyof typeof Source];

                export interface Spec {
                    action: Spec.Action;
                    fields: string[];
                    permission?: (number | null) | undefined;
                }

                export namespace Spec {
                    export const Action = {
                        All: "all",
                        Include: "include",
                        Exclude: "exclude",
                    } as const;
                    export type Action = (typeof Action)[keyof typeof Action];
                }
            }
        }
    }

    export interface Meta {
        affectedPages: Meta.AffectedPages.Item[];
        cacheDelta: Meta.CacheDelta | null;
    }

    export namespace Meta {
        export type AffectedPages = AffectedPages.Item[];

        export namespace AffectedPages {
            export interface Item {
                pageObjectNumber: number;
                revision: Item.Revision;
                weakAnnotationState: CloudPDF.DocSignaturesComplete200ResponseMetaAffectedPagesItemWeakAnnotationState;
            }

            export namespace Item {
                export interface Revision {
                    docSessionId: string;
                    pageObjectNumber: number;
                    generation: number;
                }
            }
        }

        export interface CacheDelta {
            previousDocVersion: number;
            docVersion: number;
            annotationsVersion?: number | undefined;
            layerVersion?: number | undefined;
            working?: boolean | undefined;
            pages: CacheDelta.Pages.Item[];
        }

        export namespace CacheDelta {
            export type Pages = Pages.Item[];

            export namespace Pages {
                export interface Item {
                    pageObjectNumber: number;
                    cache: Item.Cache;
                }

                export namespace Item {
                    export interface Cache {
                        contentVersion: number;
                        annotationVersion: number;
                    }
                }
            }
        }
    }
}
