// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocSignaturesComplete200ResponseSignatureField =
    | CloudPDF.DocSignaturesComplete200ResponseSignatureField.ObjectNumber
    | CloudPDF.DocSignaturesComplete200ResponseSignatureField.Fqn;

export namespace DocSignaturesComplete200ResponseSignatureField {
    export interface ObjectNumber {
        kind: "objectNumber";
        fieldObjectNumber: number;
    }

    export interface Fqn {
        kind: "fqn";
        name: string;
    }
}
