// This file was auto-generated by Fern from our API Definition.

export interface DocumentsThumbnailResponse {
    error: DocumentsThumbnailResponse.Error_;
}

export namespace DocumentsThumbnailResponse {
    export interface Error_ {
        code: string;
        message: string;
        state: string;
    }
}
