// This file was auto-generated by Fern from our API Definition.

export interface DocumentsCommit404Response {
    error: DocumentsCommit404Response.Error_;
}

export namespace DocumentsCommit404Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
