// This file was auto-generated by Fern from our API Definition.

export interface DocumentsInit400Response {
    error: DocumentsInit400Response.Error_;
}

export namespace DocumentsInit400Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
