// This file was auto-generated by Fern from our API Definition.

export interface DocumentsDelete403Response {
    error: DocumentsDelete403Response.Error_;
}

export namespace DocumentsDelete403Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
