// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocumentsInit200ResponseResumedUpload =
    | CloudPDF.DocumentsInit200ResponseResumedUpload.Presigned
    | CloudPDF.DocumentsInit200ResponseResumedUpload.Proxy;

export namespace DocumentsInit200ResponseResumedUpload {
    export interface Presigned {
        kind: "presigned";
        presigned: DocumentsInit200ResponseResumedUploadPresigned.Presigned;
        key: string;
    }

    export namespace DocumentsInit200ResponseResumedUploadPresigned {
        export interface Presigned {
            url: string;
            headers: Record<string, string>;
            method: Presigned.Method;
            expiresAt: number;
        }

        export namespace Presigned {
            export const Method = {
                Put: "PUT",
            } as const;
            export type Method = (typeof Method)[keyof typeof Method];
        }
    }

    export interface Proxy {
        kind: "proxy";
        url: string;
        key: string;
    }
}
