// This file was auto-generated by Fern from our API Definition.

export interface DocumentsDelete404Response {
    error: DocumentsDelete404Response.Error_;
}

export namespace DocumentsDelete404Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
