// This file was auto-generated by Fern from our API Definition.

export interface DocumentsImportFrom502Response {
    error: DocumentsImportFrom502Response.Error_;
}

export namespace DocumentsImportFrom502Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
