// This file was auto-generated by Fern from our API Definition.

export interface DocumentsList400Response {
    error: DocumentsList400Response.Error_;
}

export namespace DocumentsList400Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
