// This file was auto-generated by Fern from our API Definition.

export interface DocumentsUploadProxy400Response {
    error: DocumentsUploadProxy400Response.Error_;
}

export namespace DocumentsUploadProxy400Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
