// This file was auto-generated by Fern from our API Definition.

export interface DocumentsGet404Response {
    error: DocumentsGet404Response.Error_;
}

export namespace DocumentsGet404Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
