// This file was auto-generated by Fern from our API Definition.

export interface DocumentsDownload403Response {
    error: DocumentsDownload403Response.Error_;
}

export namespace DocumentsDownload403Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
