// This file was auto-generated by Fern from our API Definition.

export interface DocumentsGet403Response {
    error: DocumentsGet403Response.Error_;
}

export namespace DocumentsGet403Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
