// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocumentsInit200Response =
    | CloudPDF.DocumentsInit200Response.Created
    | CloudPDF.DocumentsInit200Response.Resumed
    | CloudPDF.DocumentsInit200Response.Deduped;

export namespace DocumentsInit200Response {
    export interface Created {
        tag: "created";
        document: DocumentsInit200ResponseCreated.Document;
        upload: CloudPDF.DocumentsInit200ResponseCreatedUpload;
    }

    export namespace DocumentsInit200ResponseCreated {
        export interface Document {
            id: string;
            tenantId: string;
            state: Document.State;
            baseSha: string | null;
            storageSizeBytes: number | null;
            metadata: Record<string, unknown> | null;
            idempotencyKey: string | null;
            failureReason: string | null;
            thumbnailState?: Document.ThumbnailState | undefined;
            thumbnailUrl?: (string | null) | undefined;
            createdAt: number;
            updatedAt: number;
            createdBy: string | null;
        }

        export namespace Document {
            export const State = {
                Pending: "pending",
                Ready: "ready",
                Failed: "failed",
                Deleting: "deleting",
            } as const;
            export type State = (typeof State)[keyof typeof State];
            export const ThumbnailState = {
                Pending: "pending",
                Ready: "ready",
                Locked: "locked",
                Failed: "failed",
            } as const;
            export type ThumbnailState = (typeof ThumbnailState)[keyof typeof ThumbnailState];
        }
    }

    export interface Resumed {
        tag: "resumed";
        document: DocumentsInit200ResponseResumed.Document;
        upload: CloudPDF.DocumentsInit200ResponseResumedUpload;
    }

    export namespace DocumentsInit200ResponseResumed {
        export interface Document {
            id: string;
            tenantId: string;
            state: Document.State;
            baseSha: string | null;
            storageSizeBytes: number | null;
            metadata: Record<string, unknown> | null;
            idempotencyKey: string | null;
            failureReason: string | null;
            thumbnailState?: Document.ThumbnailState | undefined;
            thumbnailUrl?: (string | null) | undefined;
            createdAt: number;
            updatedAt: number;
            createdBy: string | null;
        }

        export namespace Document {
            export const State = {
                Pending: "pending",
                Ready: "ready",
                Failed: "failed",
                Deleting: "deleting",
            } as const;
            export type State = (typeof State)[keyof typeof State];
            export const ThumbnailState = {
                Pending: "pending",
                Ready: "ready",
                Locked: "locked",
                Failed: "failed",
            } as const;
            export type ThumbnailState = (typeof ThumbnailState)[keyof typeof ThumbnailState];
        }
    }

    export interface Deduped {
        tag: "deduped";
        document: DocumentsInit200ResponseDeduped.Document;
    }

    export namespace DocumentsInit200ResponseDeduped {
        export interface Document {
            id: string;
            tenantId: string;
            state: Document.State;
            baseSha: string | null;
            storageSizeBytes: number | null;
            metadata: Record<string, unknown> | null;
            idempotencyKey: string | null;
            failureReason: string | null;
            thumbnailState?: Document.ThumbnailState | undefined;
            thumbnailUrl?: (string | null) | undefined;
            createdAt: number;
            updatedAt: number;
            createdBy: string | null;
        }

        export namespace Document {
            export const State = {
                Pending: "pending",
                Ready: "ready",
                Failed: "failed",
                Deleting: "deleting",
            } as const;
            export type State = (typeof State)[keyof typeof State];
            export const ThumbnailState = {
                Pending: "pending",
                Ready: "ready",
                Locked: "locked",
                Failed: "failed",
            } as const;
            export type ThumbnailState = (typeof ThumbnailState)[keyof typeof ThumbnailState];
        }
    }
}
