// This file was auto-generated by Fern from our API Definition.

export interface DocumentsCommit200Response {
    document: DocumentsCommit200Response.Document;
}

export namespace DocumentsCommit200Response {
    export interface Document {
        id: string;
        tenantId: string;
        state: Document.State;
        baseSha: string | null;
        storageSizeBytes: number | null;
        metadata: Record<string, unknown> | null;
        idempotencyKey: string | null;
        failureReason: string | null;
        thumbnailState?: Document.ThumbnailState | undefined;
        thumbnailUrl?: (string | null) | undefined;
        createdAt: number;
        updatedAt: number;
        createdBy: string | null;
    }

    export namespace Document {
        export const State = {
            Pending: "pending",
            Ready: "ready",
            Failed: "failed",
            Deleting: "deleting",
        } as const;
        export type State = (typeof State)[keyof typeof State];
        export const ThumbnailState = {
            Pending: "pending",
            Ready: "ready",
            Locked: "locked",
            Failed: "failed",
        } as const;
        export type ThumbnailState = (typeof ThumbnailState)[keyof typeof ThumbnailState];
    }
}
