// This file was auto-generated by Fern from our API Definition.

export interface DocumentsImportFrom400Response {
    error: DocumentsImportFrom400Response.Error_;
}

export namespace DocumentsImportFrom400Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
