// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export interface DocumentActionsSnapshot {
    nameTreeScripts: DocumentActionsSnapshot.NameTreeScripts.Item[];
    openAction: CloudPDF.PdfActionTree | null;
    openDestination?: (CloudPDF.PdfDestination | null) | undefined;
    willClose?: CloudPDF.PdfActionTree | undefined;
    willSave?: CloudPDF.PdfActionTree | undefined;
    didSave?: CloudPDF.PdfActionTree | undefined;
    willPrint?: CloudPDF.PdfActionTree | undefined;
    didPrint?: CloudPDF.PdfActionTree | undefined;
}

export namespace DocumentActionsSnapshot {
    export type NameTreeScripts = NameTreeScripts.Item[];

    export namespace NameTreeScripts {
        export interface Item {
            name: string;
            action: CloudPDF.PdfActionTree;
        }
    }
}
