// This file was auto-generated by Fern from our API Definition.

export interface DocumentsImportFrom403Response {
    error: DocumentsImportFrom403Response.Error_;
}

export namespace DocumentsImportFrom403Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
