// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocVersionsSignatures200ResponseSignaturesItemField =
    | CloudPDF.DocVersionsSignatures200ResponseSignaturesItemField.ObjectNumber
    | CloudPDF.DocVersionsSignatures200ResponseSignaturesItemField.Fqn;

export namespace DocVersionsSignatures200ResponseSignaturesItemField {
    export interface ObjectNumber {
        kind: "objectNumber";
        fieldObjectNumber: number;
    }

    export interface Fqn {
        kind: "fqn";
        name: string;
    }
}
