// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export interface PdfAnnotationActions {
    activate?: CloudPDF.PdfActionTree | undefined;
    cursorEnter?: CloudPDF.PdfActionTree | undefined;
    cursorExit?: CloudPDF.PdfActionTree | undefined;
    mouseDown?: CloudPDF.PdfActionTree | undefined;
    mouseUp?: CloudPDF.PdfActionTree | undefined;
    focus?: CloudPDF.PdfActionTree | undefined;
    blur?: CloudPDF.PdfActionTree | undefined;
    pageOpen?: CloudPDF.PdfActionTree | undefined;
    pageClose?: CloudPDF.PdfActionTree | undefined;
    pageVisible?: CloudPDF.PdfActionTree | undefined;
    pageInvisible?: CloudPDF.PdfActionTree | undefined;
}
