// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export interface PdfFieldActions {
    keystroke?: CloudPDF.PdfActionTree | undefined;
    format?: CloudPDF.PdfActionTree | undefined;
    validate?: CloudPDF.PdfActionTree | undefined;
    calculate?: CloudPDF.PdfActionTree | undefined;
}
