// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export interface PdfPageActions {
    open?: CloudPDF.PdfActionTree | undefined;
    close?: CloudPDF.PdfActionTree | undefined;
}
