// This file was auto-generated by Fern from our API Definition.

export interface SharesExchange400Response {
    error: SharesExchange400Response.Error_;
}

export namespace SharesExchange400Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
