// This file was auto-generated by Fern from our API Definition.

export interface SharesList200Response {
    shares: SharesList200Response.Shares.Item[];
    nextCursor?: (string | null) | undefined;
}

export namespace SharesList200Response {
    export type Shares = Shares.Item[];

    export namespace Shares {
        export interface Item {
            id: string;
            tenantId: string;
            docId: string;
            layerName: string;
            scope: string[];
            origins: string[] | null;
            passwordProtected: boolean;
            sessionTtlSeconds: number;
            disabled: boolean;
            expiresAt: number | null;
            exchangeCount: number;
            lastExchangedAt: number | null;
            createdBy: string;
            createdAt: number;
            updatedAt: number;
        }
    }
}
