// This file was auto-generated by Fern from our API Definition.

export interface SharesUpdate400Response {
    error: SharesUpdate400Response.Error_;
}

export namespace SharesUpdate400Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
