// This file was auto-generated by Fern from our API Definition.

export interface SharesCreate404Response {
    error: SharesCreate404Response.Error_;
}

export namespace SharesCreate404Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
