// This file was auto-generated by Fern from our API Definition.

export interface SharesCreate403Response {
    error: SharesCreate403Response.Error_;
}

export namespace SharesCreate403Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
