// This file was auto-generated by Fern from our API Definition.

export interface SharesGet404Response {
    error: SharesGet404Response.Error_;
}

export namespace SharesGet404Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
