// This file was auto-generated by Fern from our API Definition.

export interface SharesGet200Response {
    share: SharesGet200Response.Share;
}

export namespace SharesGet200Response {
    export interface Share {
        id: string;
        tenantId: string;
        docId: string;
        layerName: string;
        scope: string[];
        origins: string[] | null;
        passwordProtected: boolean;
        sessionTtlSeconds: number;
        disabled: boolean;
        expiresAt: number | null;
        exchangeCount: number;
        lastExchangedAt: number | null;
        createdBy: string;
        createdAt: number;
        updatedAt: number;
    }
}
