// This file was auto-generated by Fern from our API Definition.

export interface SharesExchange404Response {
    error: SharesExchange404Response.Error_;
}

export namespace SharesExchange404Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
