// This file was auto-generated by Fern from our API Definition.

export interface SharesCreate400Response {
    error: SharesCreate400Response.Error_;
}

export namespace SharesCreate400Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
