// This file was auto-generated by Fern from our API Definition.

export interface SharesExchange403Response {
    error: SharesExchange403Response.Error_;
}

export namespace SharesExchange403Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
