// This file was auto-generated by Fern from our API Definition.

export interface SharesUpdate404Response {
    error: SharesUpdate404Response.Error_;
}

export namespace SharesUpdate404Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
