// This file was auto-generated by Fern from our API Definition.

export interface TenantsGet200Response {
    tenant: TenantsGet200Response.Tenant;
}

export namespace TenantsGet200Response {
    export interface Tenant {
        id: string;
        name: string;
        autoProvisioned: boolean;
        status?: Tenant.Status | undefined;
        createdAt: number;
    }

    export namespace Tenant {
        export const Status = {
            Active: "active",
            Suspended: "suspended",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];
    }
}
