// This file was auto-generated by Fern from our API Definition.

export interface TenantsDeleteResponse {
    error: TenantsDeleteResponse.Error_;
}

export namespace TenantsDeleteResponse {
    export interface Error_ {
        code: string;
        message: string;
    }
}
