// This file was auto-generated by Fern from our API Definition.

export interface TenantsUsage400Response {
    error: TenantsUsage400Response.Error_;
}

export namespace TenantsUsage400Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
