// This file was auto-generated by Fern from our API Definition.

export interface TenantsUsage404Response {
    error: TenantsUsage404Response.Error_;
}

export namespace TenantsUsage404Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
