// This file was auto-generated by Fern from our API Definition.

export interface TenantsCreate400Response {
    error: TenantsCreate400Response.Error_;
}

export namespace TenantsCreate400Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
