// This file was auto-generated by Fern from our API Definition.

export interface TenantsUsage200Response {
    tenantId: string;
    periodStart: string;
    periodEnd: string;
    metrics: TenantsUsage200Response.Metrics;
}

export namespace TenantsUsage200Response {
    export interface Metrics {
        "pdf.views": number;
        "pdf.uploads": number;
        "storage.bytes": number;
    }
}
