// This file was auto-generated by Fern from our API Definition.

export interface TokensIssue400Response {
    error: TokensIssue400Response.Error_;
}

export namespace TokensIssue400Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
