// This file was auto-generated by Fern from our API Definition.

export interface TokensIssue403Response {
    error: TokensIssue403Response.Error_;
}

export namespace TokensIssue403Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
