// This file was auto-generated by Fern from our API Definition.

export interface TokensRevokeResponse {
    error: TokensRevokeResponse.Error_;
}

export namespace TokensRevokeResponse {
    export interface Error_ {
        code: string;
        message: string;
    }
}
