// This file was auto-generated by Fern from our API Definition.

export interface TokensIssue404Response {
    error: TokensIssue404Response.Error_;
}

export namespace TokensIssue404Response {
    export interface Error_ {
        code: string;
        message: string;
    }
}
