// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         tenantId: "tenantId",
 *         id: "id",
 *         sha256: "sha256"
 *     }
 */
export interface DocumentsCommitRequest {
    tenantId: string;
    id: string;
    sha256: string;
}
