// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         tenantId: "tenantId",
 *         id: "id"
 *     }
 */
export interface DownloadDocumentsRequest {
    tenantId: string;
    id: string;
}
