// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../../../../index.js";

/**
 * @example
 *     {
 *         tenantId: "tenantId"
 *     }
 */
export interface ListDocumentsRequest {
    tenantId: string;
    limit?: number;
    cursor?: string;
    state?: CloudPDF.ListDocumentsRequestState;
}
