// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../core/index.js";

/**
 * @example
 *     {
 *         file: fs.createReadStream("/path/to/your/file"),
 *         tenantId: "tenantId",
 *         id: "id"
 *     }
 */
export interface UploadProxyDocumentsRequest {
    tenantId: string;
    id: string;
    file: core.file.Uploadable;
}
