// This file was auto-generated by Fern from our API Definition.

import * as CloudPDF from "../../../src/api/index";
import { CloudPDFClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("RedactionsClient", () => {
    test("apply (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = {
            meta: {
                affectedPages: [
                    {
                        pageObjectNumber: 1,
                        revision: { docSessionId: "docSessionId", pageObjectNumber: 1, generation: 1 },
                        weakAnnotationState: { kind: "unknown" },
                    },
                ],
                cacheDelta: {
                    previousDocVersion: 1,
                    docVersion: 1,
                    pages: [{ pageObjectNumber: 1, cache: { contentVersion: 1, annotationVersion: 1 } }],
                },
            },
        };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/redactions/apply")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.doc.redactions.apply({
            docId: "docId",
            layerName: "layerName",
            body: {
                key: "value",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("apply (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/redactions/apply")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.redactions.apply({
                docId: "docId",
                layerName: "layerName",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.BadRequestError);
    });

    test("apply (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CloudPDFClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/docs/docId/layers/layerName/redactions/apply")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.doc.redactions.apply({
                docId: "docId",
                layerName: "layerName",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(CloudPDF.NotFoundError);
    });
});
