// Generated by scripts/generate-api-reference.mjs. Do not edit.
export default {
  list: 'List',
  analysis: 'Analysis',
  download: 'Download',
  revision: 'Revision',
  signatures: 'Signatures',
  'signature-contents': 'Signature Contents',
  'signature-digest': 'Signature Digest',
};
